### ISSUE TITLE
Error on select a text on username textfield (Login Screen)

### ISSUE THREAD

**Issue by bardez** [NearHuscarl/flutter_login#100]
**Describe the bug**
Error on select a text on username textfield (Login Screen)

**To Reproduce**
1. Go to username TextField
2. Click and press to select

**Expected behavior**
Select the text or has a option to paste

**Information (please complete the following information):**
 - Device: Any Android Device
 - Platform Android
 - Flutter version: 1.24.0-8.0-pre.356
 - Package version 1.0.14

**Additional context**

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#4e35c](dirty, state: _OverlayEntryWidgetState#fbe7a):
No MediaQuery widget ancestor found.

_OverlayEntryWidget widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was: _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#4e35c]
    dirty
    state: _OverlayEntryWidgetState#fbe7a
The ownership chain for the affected widget is: "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#4e35c] ← _Theatre ← Overlay-[LabeledGlobalKey<OverlayState>#0d090] ← Directionality ← LoadingProvider-[LabeledGlobalKey<_LoadingProviderState>#847fe] ← FutureBuilder<FirebaseApp> ← AppWidget ← ModularApp ← [root]"

No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.

The relevant error-causing widget was
LoadingProvider-[LabeledGlobalKey<_LoadingProviderState>#847fe]
lib/app/app_widget.dart:29
When the exception was thrown, this was the stack
#0      debugCheckHasMediaQuery.<anonymous closure>
package:flutter/…/widgets/debug.dart:218
#1      debugCheckHasMediaQuery
package:flutter/…/widgets/debug.dart:233
#2      _MaterialTextSelectionControls.buildToolbar
package:flutter/…/material/text_selection.dart:751
#3      TextSelectionOverlay._buildToolbar
package:flutter/…/widgets/text_selection.dart:576
#4      _OverlayEntryWidgetState.build
package:flutter/…/widgets/overlay.dart:208
...

**Comment by surister** [comment]
Did you solve it? What was the issue?

**Comment by bardez** [comment]
> Did you solve it? What was the issue?

I closed this issue because the problem was with my app structure, and not with plugin, specifically with a LOADING PROVIDER problem on my MaterialApp Structure.
