### ISSUE TITLE
gow to add extra textfeild for adding phone number   

### ISSUE THREAD

**Issue by pradeepslnp** [NearHuscarl/flutter_login#102]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by SalahAdDin** [comment]
Can you update this?

**Comment by juliansteenbakker** [comment]
Adding extra fields will be tracked in #54
