### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by mjablecnik** [NearHuscarl/flutter_login#103]
@NearHuscarl 
Is this project dead? Because I see a lot of PR or Issues which is nobody resolving for last year..

**Comment by JohnBerd** [comment]
Maybe a new maintainer could fork it

**Comment by juliansteenbakker** [comment]
I have contacted @NearHuscarl via mail with the question if i could be a maintainer. Let's hope he responds.

**Comment by lcsvcn** [comment]
@NearHuscarl @doc-rj-celltrak Can you add more people to maintain this repository? This project is to awesome to be left dead! I would volunteer me to help review some PR and help you maintain it. I think other devs may also be able to help you keep this repository updated.

**Comment by lcsvcn** [comment]
@juliansteenbakker Any response? It would be awesome to get some updates to this project, like add null-safety.

**Comment by lcsvcn** [comment]
@juliansteenbakker if you want to help me update this repo and maintain, I have created an organization and forked, if the maintainers of this repo answer you we can ask to merge our changes with their code.

https://github.com/BoringDevelopmentTeam/flutter_login

**Comment by juliansteenbakker** [comment]
Yes i'm in contact with @NearHuscarl. I'll keep you up to date on when i get maintainer rights.

**Comment by juliansteenbakker** [comment]
See https://github.com/NearHuscarl/flutter_login/issues/108 for more info. Happy to get started fixing some issues!
