### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by lcsvcn** [NearHuscarl/flutter_login#106]
Description:

- Migrate to sound null safety
- Bump up package version

**Comment by juliansteenbakker** [comment]
Blocked by #109

**Comment by juliansteenbakker** [comment]
Delayed because of some functionality with priority.

**Comment by SalahAdDin** [comment]
May the next error be related to this?
```bash
[cancer-tez-project] flutter pub get
Running "flutter pub get" in cancer-tez-project...              
Because no versions of flutter_login match >1.0.15 <2.0.0 and flutter_login 1.0.15 depends on provider ^4.0.2, flutter_login ^1.0.15 requires provider ^4.0.2.

And because flutter_bloc >=7.0.0-nullsafety.4 depends on provider ^5.0.0, flutter_login ^1.0.15 is incompatible with flutter_bloc >=7.0.0-nullsafety.4.

So, because thesis_cancer depends on both flutter_bloc ^7.0.0 and flutter_login ^1.0.15, version solving failed.
pub get failed (1; So, because thesis_cancer depends on both flutter_bloc ^7.0.0 and flutter_login ^1.0.15, version solving failed.)
exit code 1
```

**Comment by juliansteenbakker** [comment]
The past few days i've worked on a null-safety version. I have uploaded the version to the `null-safety` branch. There are however still some issues with it. For instance, some tests aren't working right now because of some wrong types. It would be great of someone could help me with this and check the code and fix bugs where needed.

When all tests are working and everything seems good to go, I'll make a pull requests which then again needs to be checked by someone.

**Comment by lcsvcn** [comment]
Hi @juliansteenbakker 

I have fixed the remaining tests after null safety refactor.

https://github.com/NearHuscarl/flutter_login/pull/131

**Comment by lcsvcn** [comment]
@juliansteenbakker Should Null Safety migration be a milestone for version **2.0.0** instead of **1.2.0**? 

In my opinion, Null Safety may be consider as a Major version upgrade, since it is a breaking change to any library that introduces it, requiring app to support dart version 2.12 and above.

<img src="https://user-images.githubusercontent.com/6011385/112910728-63609680-90ca-11eb-8713-629392252ee5.png" alt="alt text" width="350" height="150">

**Comment by juliansteenbakker** [comment]
Good catch, I will use 2.0.0 for null-safety.

**Comment by juliansteenbakker** [comment]
I have published first pre-release of null-safety under version 2.0.0-nullsafety.0 and i will merge this with master as soon as others have checked the code for possible improvements. Please see #138.

**Comment by SalahAdDin** [comment]
@juliansteenbakker everything is ok here! Thanks!
I just opened another [issue](https://github.com/NearHuscarl/flutter_login/issues/144), maybe i can help with it.
