### ISSUE TITLE
Please do a tutorial with a simple login and signup and teach how to use it or implement it..

### ISSUE THREAD

**Issue by fisforfaheem** [NearHuscarl/flutter_login#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by surister** [comment]
You have an example in the example folder

**Comment by fisforfaheem** [comment]
No, bro i am a beginner and don't know how to use it...i mean a very basic
step by step guide please

**Comment by Lorenzohidalgo** [comment]
The documentation is quite good. you can check this [tutorial](https://www.youtube.com/watch?v=x8xEkNCd3Vg&t=5s) if you need help implementing it.

**Comment by fisforfaheem** [comment]
Thanks but if u got some time on a weekend do make a basic tutorials and
let me know,
