### ISSUE TITLE
[BLOCKING] Flushbar not recognized in widget test

### ISSUE THREAD

**Issue by juliansteenbakker** [NearHuscarl/flutter_login#109]
For source code, check the `pedantic` branch.

**Describe the bug**
After updating the package to null-safety and replacing various deprecated elements with up to date widgets, i can't seem to get the widget test working. It seems that it can't find the text from the flushbar. 

Test Password recovery should show success message if email is valid: 
```dart
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "User not exists" (ignoring offstage widgets)>
   Which: means none were found but one was expected
```

**To Reproduce**
1. Run tests in `pedantic` branch.

**Expected behavior**
Test should find the text and pass the test.

**Information (please complete the following information):**
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.1 20D74 darwin-x64, locale nl-NL)
    • Flutter version 2.0.2 at /Users/bever/Documents/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

**Additional context**
This problem is blocking further development since tests are required to pass in this project.

**Comment by MiroLiebschner** [comment]
Is the blocking issue resolved?

**Comment by juliansteenbakker** [comment]
@MiroLiebschner Yes it is solved
