### ISSUE TITLE
[FEATURE] Decrease animations

### ISSUE THREAD

**Issue by everters** [NearHuscarl/flutter_login#122]
**Is your feature request related to a problem? Please describe.**

Sometimes animations really feel too much. For us, it might be much better to have simpler transition that last less time. 

**Describe the solution you'd like**

It would be great to skip some of the animations / have simplified animations / have no animations at all when a flag is set.

**Comment by juliansteenbakker** [comment]
This package is built by @NearHuscarl to show the animation capabilities of Flutter. It would be against his idea for building this package to remove these animations. You are however free to fork this repo and make any changes to it yourself.
