### ISSUE TITLE
BoxConstraints has a negative minimum height. The relevant error-causing widget was: 

### ISSUE THREAD

**Issue by sumitsharansatsangi** [NearHuscarl/flutter_login#123]
I was trying to run the example app and got negative minimum height error.
![Screenshot at 2021-03-23 14-55-37](https://user-images.githubusercontent.com/45959281/112125807-b8c51100-8bbb-11eb-974f-0d0089425ce6.png)

I was trying to built for tablet
 - Flutter version: [  2.1.0 ]
 - Package version [e.g. 1.0.15]

**Additional context**

When I tried building for Linux I get another issue.

![Screenshot at 2021-03-23 15-13-31](https://user-images.githubusercontent.com/45959281/112126353-47399280-8bbc-11eb-8f82-fe02ed14c9cd.png)

**Comment by juliansteenbakker** [comment]
The first issue only happens when the view is not active while the app is being opened. Because the width and height are 0, this error is thrown. The second error is tracked here #97.
