### ISSUE TITLE
Option to add keys to textfields for finding during widget tests[FEATURE] 

### ISSUE THREAD

**Issue by xapatjb4** [NearHuscarl/flutter_login#137]
**Is your feature request related to a problem? Please describe.**
I'm trying to test an email and password submission but am not able to enter text to either fields. I'm able to enter text in textfields using a key and widgetTester's finder function

**Describe the solution you'd like**
Adding a field to enter keys for different parts user can tap on (i.e. textfields, buttons etc)

**Comment by juliansteenbakker** [comment]
It would be a good addition indeed. We do however have working tests by looking which position the textfield is:
```dart
Finder findNameTextField() {
  return find.byType(TextFormField).at(0);
}

Finder findPasswordTextField() {
  return find.byType(TextFormField).at(1);
}

Finder findConfirmPasswordTextField() {
  return find.byType(TextFormField).at(2);
}
```
