### ISSUE TITLE
[FEATURE] Check box for GDPR compliance.

### ISSUE THREAD

**Issue by SergeiLabutin** [NearHuscarl/flutter_login#140]
**Is your feature request related to a problem? Please describe.**
GDPR uncompliance by default. Before sign up, user can be do not agree with receive validation code to email / phone number.

**Describe the solution you'd like**
Add checkbox into sign up view.
Button disabled and callback do not call if checkbox do not checked. This important, by default unchecked field and user press himself.
Example for text: "I agree to the **Terms of Service** and **Privacy Policy**"
Add two callbacks for each document.

**Additional context**
Random image from Google search with checkbox
![23745262](https://user-images.githubusercontent.com/16681137/113149410-a3935680-923b-11eb-8931-d42d684566dd.jpg)

**Comment by SergeyLabutin** [comment]
Also "sign up" ui is not clear. Options "forgot password" is confuses. It's option for sign in view.
You can use this place for checkbox in sign up view, and animated change to "forgot password" when user switch views.
