### ISSUE TITLE
[FEATURE] LoginTheme primaryColor is limitating

### ISSUE THREAD

**Issue by PepeExpress** [NearHuscarl/flutter_login#146]
**Is your feature request related to a problem? Please describe.**
In my login screen I have a custom background with gradients, to avoid the LoginScreen to cover the background with the primaryColor I set the primaryColor to transparent. This works fine, the problem is that the SIGNUP label for example inherit the primaryColor and therefore it is transparent too and not visible.

**Describe the solution you'd like**
I would suggest to add another color property for SIGNUP label.

**Comment by axgalache** [comment]
+1
I'm bounded to have the same color for background and SIGNUP label :(
