### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jonbhanson** [NearHuscarl/flutter_login#154]
Thanks for the great package!
The documentation for the Null Safe version of the package shows various callbacks returning null, which is no longer possible with null safety.  Please show how the returns should be handled in the new version.

**Comment by t-walker-wei** [comment]
Change `return null` to `return ''`. It should works in those examples

**Comment by mafudge** [comment]
That does not seem to work. It does not matter what I enter here it always logs on. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/663345/115910519-edd2b680-a43a-11eb-8d3d-8ea33ce14722.png)

**Comment by surister** [comment]
@mafudge Share your pubspec.yml, make sure that you are using the latest `flutter_login` version.

**Comment by mafudge** [comment]
I am using 

 flutter_login: "2.0.0-nullsafety.0"
 
If my onLogin calls a function, it works but the same implementation within the onLogin does not work. If I get time I'll post an example for clarity.

**Comment by surister** [comment]
@mafudge Create a new issue

**Comment by t-walker-wei** [comment]
> That does not seem to work. It does not matter what I enter here it always logs on. Am I doing something wrong?
> 
> ![image](https://user-images.githubusercontent.com/663345/115910519-edd2b680-a43a-11eb-8d3d-8ea33ce14722.png)

I have a question for you maybe I am stupid. Why not equal  is not '!=' in your code?

**Comment by surister** [comment]
This question is beyond the topic of the Issue but..

He is using font ligatures, if I am not mistaken, it is the Fira code font.
![image](https://user-images.githubusercontent.com/37985796/117623998-b8390780-b174-11eb-9418-055e7b1545eb.png)

You can find more infomation here: https://github.com/tonsky/FiraCode

**Comment by lcsvcn** [comment]
Hi, the documentation is right.

You need to use a **Future<String?>** function

Return **null** if it has success. Return **string** with error to be shown.

```Dart
Duration get loginTime => Duration(milliseconds: 2250);

Future<String?> loginUser(LoginData data) {
   log.d('Name: ${data.name}, Password: ${data.password}');
   return Future.delayed(loginTime).then((_) async {
      /// Change this with your Sign In Logic
      /// expects [null] if success or [string] with error message.
      String? result = await _auth.doSignIn(data.name, data.password);
      return result;
   }
}


```

**Comment by lcsvcn** [comment]
@juliansteenbakker This can be closed too. It is not a bug. I have provided a brief explanation above.
