### ISSUE TITLE
Not UI well in dark mode

### ISSUE THREAD

**Issue by shinewanna** [NearHuscarl/flutter_login#160]
![Screen Shot 2021-04-23 at 3 37 32 PM](https://user-images.githubusercontent.com/39454969/115848486-ee267e00-a449-11eb-8971-10cdbcb29bc0.png)

Text Editing text value and some other text color is black.

**Comment by surister** [comment]
This is not a bug. `loginTheme` exposes everything.

Change the values in loginTheme according to 
```isDarkModeOn = MediaQuery.of(context).platformBrightness == Brightness.dark;```

```      
     theme: LoginTheme(
        textFieldStyle: TextStyle(
          color: Colors.pink,
        ),
        inputTheme: InputDecorationTheme(
          filled: true,
          fillColor: isDarkModeOn
              ? Colors.orange.withOpacity(.2)
              : Colors.black.withOpacity(.2),
        ),
      ),
```
![image](https://user-images.githubusercontent.com/37985796/115969494-78034380-a53d-11eb-90c8-bec832f91687.png)
![image](https://user-images.githubusercontent.com/37985796/115969496-7afe3400-a53d-11eb-8830-876ca9c36d2a.png)

**Comment by shinewanna** [comment]
Thanks
