### ISSUE TITLE
there are no textfield controller for textfield if i want textfield to alter or make auth with firebase.

### ISSUE THREAD

**Issue by ZubairAAC** [NearHuscarl/flutter_login#162]
there are no textfield controller for textfield if i want textfield to alter or make auth with firebase.

**Comment by SalahAdDin** [comment]
Can you explain it wider?

**Comment by maxplanckk** [comment]
How can we use this package with firebase auth?

**Comment by maxplanckk** [comment]
Thank you for your reply. I'm a beginner and unable to follow thee documentation.

**Comment by nyck33** [comment]
@SalahAdDin 
Can you show me your provider? `authNotifierProvider`?

I was trying something with a class where the Reader is a member
```
final firebaseAuthProvider = Provider((ref) => FirebaseAuth.instance);

class AuthService {
  AuthService(this._read);

  final GoogleSignIn _googleSignIn = GoogleSignIn();

  final Reader _read;

  static final authProvider = Provider((ref) => AuthService(ref.read));

  Future<User?> emailSignIn(String? email, String? password) async {
    assert(email != null && password != null);
    final auth = _read(firebaseAuthProvider);
    try {
      final UserCredential? credential = await auth.signInWithEmailAndPassword(
          email: email!, password: password!);
      assert(credential?.user != null);
      return credential!.user;
    } on FirebaseAuthException catch (e) {
      if (e.code == 'user-not-found') {
        print('No user found for that email.');
      } else if (e.code == 'wrong-password') {
        print('Wrong password provided for user');
      }
    }
  }
```
but your way looks cleaner.

**Comment by SalahAdDin** [comment]
> @SalahAdDin Can you show me your provider? `authNotifierProvider`?
> 
> I was trying something with a class where the Reader is a member
> 
> ```
> final firebaseAuthProvider = Provider((ref) => FirebaseAuth.instance);
> 
> class AuthService {
>   AuthService(this._read);
> 
>   final GoogleSignIn _googleSignIn = GoogleSignIn();
> 
>   final Reader _read;
> 
>   static final authProvider = Provider((ref) => AuthService(ref.read));
> 
>   Future<User?> emailSignIn(String? email, String? password) async {
>     assert(email != null && password != null);
>     final auth = _read(firebaseAuthProvider);
>     try {
>       final UserCredential? credential = await auth.signInWithEmailAndPassword(
>           email: email!, password: password!);
>       assert(credential?.user != null);
>       return credential!.user;
>     } on FirebaseAuthException catch (e) {
>       if (e.code == 'user-not-found') {
>         print('No user found for that email.');
>       } else if (e.code == 'wrong-password') {
>         print('Wrong password provided for user');
>       }
>     }
>   }
> ```
> 
> but your way looks cleaner.

I use this as **Provider**:
```dart
final StateNotifierProvider<AuthNotifier, AuthState> authNotifierProvider =
    StateNotifierProvider<AuthNotifier, AuthState>(
  (ProviderReference ref) => AuthNotifier(reader: ref.read),
  name: "Authentication Notifier Provider",
);
```

And my **Notifier**:
```dart
class AuthNotifier extends StateNotifier<AuthState> {
  ///
  AuthNotifier({required this.reader}) : super(const AuthState.loading());

  /// [Reader] provider reader.
  final Reader reader;

  AuthRepository get _authRepository => reader(authRepositoryProvider);

  DataStoreRepository get _dataStore => reader(dataStoreRepositoryProvider);

  StateController<User?> get _userController =>
      reader(userEntityProvider.notifier);

  StateController<String> get _tokenController =>
      reader(tokenProvider.notifier);

  fb.FirebaseAuth get _fireBaseAuth => reader(firebaseAuthProvider);

  FirebaseAnalytics get _firebaseAnalytics => reader(firebaseAnalyticsProvider);

...
}
```

**Comment by nyck33** [comment]
@SalahAdDin 
In the above snippet, what is the difference if I did:
```
late final  _authRepository = reader(authRepositoryProvider);
```
rather than what you have?

**Comment by SalahAdDin** [comment]
> @SalahAdDin In the above snippet, what is the difference if I did:
> 
> ```
> late final  _authRepository = reader(authRepositoryProvider);
> ```
> 
> rather than what you have?

how can you put `late` and `final` together?

**Comment by nyck33** [comment]
@SalahAdDin it's a lazy final variable?  Is this something that is very bad because the author of go_router is doing it in his example.

**Comment by juliansteenbakker** [comment]
> late final  _authRepository = reader(authRepositoryProvider);

Since it's final, and you already assigned something to it, it cannot be reassigned. Hence the `late` is redundant

**Comment by nyck33** [comment]
@juliansteenbakker https://stackoverflow.com/a/64046113/9481613

**Comment by SalahAdDin** [comment]
> @juliansteenbakker https://stackoverflow.com/a/64046113/9481613 @SalahAdDin I had a mixup mentally. In that case, what's the difference between the way shown above and say, `final authRepository = reader(authRepositoryProvider);`

i'm not sure if it a good practice but in my case we are creating a getter to get the provider by reading it, you are just assigning a variable.

**Comment by juliansteenbakker** [comment]
@nyck33 that was something i didn't know, thanks !

**Comment by nyck33** [comment]
@juliansteenbakker The go_router example that lead me to look up the S.O. answer: https://github.com/csells/go_router/blob/master/example/lib/nested_nav.dart
