### ISSUE TITLE
connect to sqlite shared with cloud[FEATURE] 

### ISSUE THREAD

**Issue by youssriaboelseod** [NearHuscarl/flutter_login#164]
thanks for your best backage
it easy to use
thank you

i need to connect to sqlite by sqflite

how can i do that?

**Comment by SalahAdDin** [comment]
This is not a part of this package scope, if you need that you must to plan your architecture to connect your business logic with a screen or widget who uses this package.

This package only handles the Login Screen and its related workflow, nothing more.
