### ISSUE TITLE
Flush bar doesn‘t fill the bottom area on iOS

### ISSUE THREAD

**Issue by TENX-S** [NearHuscarl/flutter_login#168]
Hi, I'm not sure if this is a bug, but the flush bar fills the bottom area on Android.

The following screenshot is from iPhone Xs Max.
![519E53F612D0156C3982BC15DD1C9157](https://user-images.githubusercontent.com/40336192/117307140-e38ccf80-aeb2-11eb-98dd-ef6790b35472.png)

**Comment by jayjah** [comment]
I am not quite sure about the intension of @NearHuscarl about this behaviour, but in generell this is treated as a safe area on ios and therefore corresponds to the os side. In addition to that, the behaviour you mentioned would violate against apples human interface guidelines. See here fore more info [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/)

**Comment by TENX-S** [comment]
Alright, I'll customize the code according to my own needs.
