### ISSUE TITLE
The named parameter 'loginProviders' isn't defined.

### ISSUE THREAD

**Issue by echarish** [NearHuscarl/flutter_login#171]
I am using  flutter_login: ^1.0.15 and when I use loginProviders while creating FlutterLogin() I am getting error saying The named parameter 'loginProviders' isn't defined. Could you point me how to fix this issue.

**Comment by SalahAdDin** [comment]
@echarish Login providers, till i know, it working with the `null-safety` version.

**Comment by SalahAdDin** [comment]
@echarish You can update to `2.0.0`, it is working right now.
