### ISSUE TITLE
[FEATURE] Either a reset password card or onSubmitAnimationCompleted after onRecoverPassword

### ISSUE THREAD

**Issue by SalahAdDin** [NearHuscarl/flutter_login#174]
**Is your feature request related to a problem? Please describe.**
Right now, working with our backend the recovering password's workflow is as follows:
- Request a recovering password code (Screen).
- Set the new password, its confirmation value and the confirmation code (Screen).
- Go to Login screen.

The current `flutter_login` allow us to reques the confirmation code by puttin the email, but nothing more. We though after requesting it will send us to the Recovery Password screen as we code, but it seems not to be the case since clicking on the recovery button does not triggers the `onSubmitAnimationCompleted` function.
 
**Describe the solution you'd like**
There are two possible solutions for this: 
either an additional card is created that is launched after requesting the code and containing redirects to the LoginScreen after sending the verification code and password (as most mobile applications do); or else the `onSubmitAnimationCompleted` function is triggered, allowing the end user to manage the recovery workflow however they want, directing them to their own screen (the fastest but less complete, since it would make it difficult for the user to be able to direct the login screen again).

What do you think? 

**Additional context**

**Comment by SalahAdDin** [comment]
I update this with:

We would ask if there is a way to customize the error messages: let's say if we want to put or longer messages, or if we want to localizate them in other languages.

Is it hard to do?

**Comment by juliansteenbakker** [comment]
Functionality is merged using a new card type and released in v3.0.0-beta.1. Thanks for the patience.
