### ISSUE TITLE
[FEATURE] I can't find "userType".

### ISSUE THREAD

**Issue by zizaihuan** [NearHuscarl/flutter_login#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by SalahAdDin** [comment]
@zizaihuan Can you describe your problem here? is this a feature issue or a bug issue?

**Comment by zizaihuan** [comment]
> @zizaihuan Can you describe your problem here? is this a feature issue or a bug issue?

I am sorry. I had find it. Haha
