### ISSUE TITLE
[Bug] I can't detect the "userType"

### ISSUE THREAD

**Issue by zizaihuan** [NearHuscarl/flutter_login#176]
**Describe the bug**
when try to use userType, I get error:
Undefined name 'LoginUserType'.
Try correcting the name to one that is defined, or defining the name.dartundefined_identifier

**To Reproduce**
1. create a FlutterLogin
2. use userType
3. find Undefined name 'LoginUserType'.

**Expected behavior**
can detect userType

**Screenshots**
![error](https://user-images.githubusercontent.com/43963067/119746369-f21f4300-bec2-11eb-872f-26987e78b365.jpg)

**Information (please complete the following information):**
**Additional context**
I have find the file in login_user_type
so I add 
// ignore: implementation_imports
import 'package:flutter_login/src/models/login_user_type.dart';
Now it can be detected.

**Comment by JAVPHP** [comment]
![image](https://user-images.githubusercontent.com/48326762/120149447-5112ee00-c21c-11eb-9d9e-0f3bab056a8e.png)

**Comment by JAVPHP** [comment]
Don't import implementation files from another package

**Comment by JAVPHP** [comment]
https://github.com/NearHuscarl/flutter_login/pull/172/commits/274f53e4e5b35f026643a7a7ecaed05a5d311fd1
it work

**Comment by malta895** [comment]
Fixed in #172

**Comment by zizaihuan** [comment]
> Fixed in #172

Ok, now It works.
