### ISSUE TITLE
[FEATURE]provide more choices, not only two row.

### ISSUE THREAD

**Issue by zizaihuan** [NearHuscarl/flutter_login#177]
**Is your feature request related to a problem? Please describe.**
the problem is I would like to register with emal(can recover the password), username(used to login) and password(used to login), but these are not choices.
I wonder more scalability.

**Describe the solution you'd like**
maybe provide a row with a validator is good, It means you can provide a List for row and a corresponding List for validator, their lengths should be equal.
there is a situation that we may provide a function "login/sign up with phone number with one button", in this case, we only provide one button use to login/sign up for user. That means we don't need those two rows. We only need login/sign up button, if use two List to define( I suggest above ), then we can do these only  provide two empty List.

**Comment by SalahAdDin** [comment]
I think there is a issue related to this: adding more fields to the signup form.

**Comment by SalahAdDin** [comment]
I think there is a issue related to this: adding more fields to the signup form.

**Comment by zizaihuan** [comment]
> I think there is a issue related to this: adding more fields to the signup form.

Not only add more, but can also just provide one or none( just provide the button).
I think the advantage of flutter_login is its elegant and smooth animation, based on this it's better to provide more flexibility.

**Comment by SalahAdDin** [comment]
I think it is related to this: https://github.com/NearHuscarl/flutter_login/issues/54

**Comment by juliansteenbakker** [comment]
Closing this as duplicate of #54
