### ISSUE TITLE
latest version of flutter login (1.1.0) is incompatible with latest version of firebase core (0.7.0)

### ISSUE THREAD

**Issue by kaleballmon** [NearHuscarl/flutter_login#178]
Description:
When using `flutter pub get` with the latest version of Flutter Login and the latest version of Firebase Core in pubspec.yaml dependencies, `flutter pub get` fails because the two versions are incompatible. They require different versions of the quiver package.

To Reproduce:
1. Add `firebase_core: ^0.7.0` and `flutter_login: ^1.1.0` under dependencies in pubspec.yaml
2. run `flutter pub get` in the project root.
3. See Error: 
    "Because no versions of flutter_login match >1.1.0 <2.0.0 and flutter_login 1.1.0 **depends on quiver ^3.0.0**, flutter_login ^1.1.0 requires quiver ^3.0.0.

And because firebase_core >=0.7.0 <0.8.0-1.0.nullsafety.0 **depends on quiver ^2.0.0**, flutter_login ^1.1.0 is incompatible with firebase_core >=0.7.0 <0.8.0-1.0.nullsafety.0.

So, because [project name] depends on both firebase_core ^0.7.0 and flutter_login ^1.1.0, version solving failed."

Expected behavior:
I expect both of these packages to work together with the latest stable versions of each.

Screenshots:
<img width="1177" alt="Screen Shot 2021-05-26 at 9 42 36 PM" src="https://user-images.githubusercontent.com/56810618/119757981-5f06ee80-be6b-11eb-878a-fbc07ee4321f.png">

Environment:
 - Device: Macbook Air M1 2020
 - OS: OSX Big Sur 11.2.1
 - Flutter version: 1.12.13
 - Package version: 1.10

**Comment by SalahAdDin** [comment]
@kaleballmon Did you try with the `null-safety` version?

**Comment by kaleballmon** [comment]
@SalahAdDin Perfect, that was it. I had to upgrade all of my firebase dependencies to the `null-safety` version. Thank you!
