### ISSUE TITLE
Enhancement: support addition of oauth signup/authentication loops

### ISSUE THREAD

**Issue by PeterGrace** [NearHuscarl/flutter_login#18]
I love your code for flutter_login and am using it in my application along with Firebase for authentication.  Firebase supports enabling other auth providers beyond user/pass, including Google, Twitter, Facebook, etc.  I'd really love it if I could incorporate those into my login widget, perhaps triggering an alternate event (onOAuth as opposed to onLogin?)

What I'm envisioning is a bar either above or below the login/pass fields that has a Column() populated with Button(Icon())'s of the services, and upon hitting the button we'd get a triggered onOAuth with an argument that specifies which service? 

Is this something worth adding?

**Comment by feliwir** [comment]
Interested in this aswell for Google-SignIn

**Comment by xnio94** [comment]
any news on this

**Comment by xnio94** [comment]
i made this [patch](https://github.com/NearHuscarl/flutter_login/pull/79) it should add support to any auth providers like google Facebook....

**Comment by juliansteenbakker** [comment]
This is added in #79.
