### ISSUE TITLE
Hide Buttons

### ISSUE THREAD

**Issue by TheParthShah** [NearHuscarl/flutter_login#19]
Hey,

I have tried using the library. I wanted to know if I only want to use Sign In option and not SignUp option then how can I hide the SignUp button and forget password button

**Comment by Ahmedmedhat187** [comment]
Hey,

I have same issue, I want to use this library without Sign Up button

**Comment by cemtuna** [comment]
Hi there,
I want to have option to hide/show buttons too. It needs to develop.
I did some change in my local.

in auth_card.dart file, comment line below and finally signup button is hide
//_buildSwitchAuthButton(theme, messages),

**Comment by cemtuna** [comment]
> Hi there,
> I want to have option to hide/show buttons too. It needs to develop.
> I did some change in my local.
> 
> in auth_card.dart file, comment line below and finally signup button is hide
> //_buildSwitchAuthButton(theme, messages),

And this tool is perfect and useful. thanks to developer

**Comment by evertonAlvaro** [comment]
I added this feature in my fork
https://github.com/NearHuscarl/flutter_login/issues/20#issuecomment-565536482

**Comment by TrueGeek** [comment]
@evertonAlvaro I'd love these features as well. If @NearHuscarl is interested, can you submit your changes as a PR?

**Comment by evertonAlvaro** [comment]
@TrueGeek I already submitted with the changes by PR. Waiting for him.

**Comment by On365** [comment]
I also develop this feature, apparently it will not be added. how are you doing with the package so as not to change what you did?

**Comment by On365** [comment]
I also developed this feature, in case it is not added. how are you doing with the package so as not to change what you did?

**Comment by Emondroid-GitHub** [comment]
Hey,

This is the way how we can remove the signup button.

Remove the methods below:

- onSignUp
- onConfirmSignup
- additionalSignupFields
 
After that, you will notice the signup button is disappeared.
