### ISSUE TITLE
idea - confirm your account

### ISSUE THREAD

**Issue by doc-rj-celltrak** [NearHuscarl/flutter_login#2]
This is really beautifully done, thanks! Here's an idea to make it even nicer. It would be great to support a full sign-up flow, including entry of a confirmation code to confirm the account.

It could be an optional feature. The "confirm account" card would be a child of the auth card page transformer. When user clicks on "sign up" button, it would switch to the "confirm account" card after calling back to client's AuthCallback onSignup (which triggers the email with confirmation code).

The content of the card would be similar to this screenshot, without the username field (but much slicker in your library, of course). One client callback would be tied to the "confirm" button. Another client callback would be tied to the "resend code" button. The "resend code" button could also trigger another page transform to visualize resending the code.

![Screenshot_1573362773](https://user-images.githubusercontent.com/55109813/68539439-5dd5a580-0349-11ea-983f-526663716b06.png)

Along these same lines, it would be great if the password recovery card supported a mode where you enter a verification code along with your password, similar to the screenshot below.

![Screenshot_1573364591](https://user-images.githubusercontent.com/55109813/68539547-0fc1a180-034b-11ea-8905-fa5542d306cb.png)

The screenshots were taken from this AWS Cognito sample app: https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo

**Comment by juliansteenbakker** [comment]
Will be fixed with #15 and other changes present in confirmation-card branch. Thank you for your contribution.
