### ISSUE TITLE
Render Overflow Exceptions

### ISSUE THREAD

**Issue by doc-rj-celltrak** [NearHuscarl/flutter_login#20]
Exceptions happen when using flutter_login on lower resolution screens. Here's an example on a Nexus 4 (768 x 1280 xhdpi):

Another exception was thrown: A RenderFlex overflowed by 17 pixels on the bottom.

![Screenshot_1575527407](https://user-images.githubusercontent.com/55109813/70209703-94a79d00-16f6-11ea-9585-f91e2bfabc2a.png)

**Comment by dat0935** [comment]
you can set 
"final headerHeight = deviceSize.height * .3;" -->
"final headerHeight = deviceSize.height * .6;" in file "flutter_login.dart" to fix it.
That's my fix.

**Comment by evertonAlvaro** [comment]
My phone also happens that. I fork, solved the problem and add more features.
![image](https://user-images.githubusercontent.com/17398036/70820100-93413900-1db6-11ea-9495-16b9aacc5917.png)

**Comment by evertonAlvaro** [comment]
My phone also happens that. I fork, solved the problem and add more features.
https://github.com/evertonAlvaro/flutter_login
![image](https://user-images.githubusercontent.com/17398036/70820150-b7047f00-1db6-11ea-8e7d-41baa20e402e.png)

**Comment by muziling** [comment]
hope can merge to this branch

**Comment by NearHuscarl** [comment]
The fix is to simply hide the logo if there is not enough room. Open the issue again if you still have any troubles.

**Comment by nyck33** [comment]
@NearHuscarl Happening in version 3.0.0 on an Alcatel 1B.
