### ISSUE TITLE
Active input's icon and label does not match with theme main color

### ISSUE THREAD

**Issue by SalahAdDin** [NearHuscarl/flutter_login#200]
**Describe the bug**
Active input's icon and label color don't match with the main theme color.

**To Reproduce**
1. Just change the theme primary color to another color.

**Expected behavior**
Both icon and text should have the same color as the main color text.

**Screenshots**
![image](https://user-images.githubusercontent.com/5034215/125811655-6b4acf45-326b-4d61-a799-c97ff1b38198.png)

**Information (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - Platform [e.g. mobile, web]
 - Flutter version: 2.2.3
 - Package version: 2.1.0

**Additional context**

**Comment by juliansteenbakker** [comment]
Merged

**Comment by bilalhammoud** [comment]
Bug is not fixed for Cupertino apps

**Comment by SalahAdDin** [comment]
> Bug is not fixed for Cupertino apps

@juliansteenbakker
