### ISSUE TITLE
Transparent/Invisible buttons "switch to signup/login" and "go back"

### ISSUE THREAD

**Issue by alexw92** [NearHuscarl/flutter_login#210]
**Describe the bug**
The buttons used to switch to SignUp or Login mode respectively (below the login button) as well as the "Go Back" button (below the "recovery" button) in the password forget view are transparent.  The buttons are there and react to clicks but they are not visible.

**To Reproduce**
Run the app provided in the example folder. 

**Expected behavior**
The mentioned buttons to be non-transparent.

**Screenshots**
![back_button_invisible](https://user-images.githubusercontent.com/9419583/126871422-378deea3-5c0b-447f-b927-835726a21b50.PNG)
![signup_button_invisible](https://user-images.githubusercontent.com/9419583/126871424-d780dadd-695b-40a2-8243-a6dcaf022576.PNG)

**Information (please complete the following information):**
 - Flutter version: [2.2.3 ]
 - Package version [2.2.2] but I also tried 2.2.1 and 2.2.0 with same behavior
 - Tested on Physical Android device and Web

**Comment by juliansteenbakker** [comment]
Thank you, i am aware of this problem and will publish a fix for it tomorrow.

**Comment by imtimera** [comment]
Hi @juliansteenbakker , I use flutter_login 2.2.1 but the problem is still there for goBackButton on recoverypassword screen:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/16920122/127660662-58d0ea83-dfbc-4825-ba0a-935fb0bd9373.png">

thanks!

**Comment by yogithesymbian** [comment]
> Hi @juliansteenbakker , I use flutter_login 2.2.1 but the problem is still there for goBackButton on recoverypassword screen:
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/16920122/127660662-58d0ea83-dfbc-4825-ba0a-935fb0bd9373.png">
> 
> thanks!

me too ..  i have tried with ```flutter_login: ^2.2.1```

**Comment by denghejun** [comment]
flutter_login: ^2.2.1 still got this issue.

**Comment by denghejun** [comment]
> LoginButtonTheme



> > Hi @juliansteenbakker , I use flutter_login 2.2.1 but the problem is still there for goBackButton on recoverypassword screen:
> > <img alt="image" width="309" src="https://user-images.githubusercontent.com/16920122/127660662-58d0ea83-dfbc-4825-ba0a-935fb0bd9373.png">
> > thanks!
> 
> me too .. i have tried with `flutter_login: ^2.2.1` and get on same problem
> my solution is make a button shadow into more shadow
> 
> ```
>         buttonTheme: LoginButtonTheme(
>           splashColor: Colors.indigo,
>           backgroundColor: Colors.indigo.shade400,
>           // highlightColor: Colors.lightGreen,
>           elevation: 20.0, // increase ,
> ```

But I got LoginButtonTheme  can not be assingn to buttonThemeData
