### ISSUE TITLE
It is not possible to put primary color as input label

### ISSUE THREAD

**Issue by SalahAdDin** [NearHuscarl/flutter_login#212]
**Describe the bug**
Well, we have a problem here: what if we want the text to be like the primary color? Your change oberseeded mine and now we can't see the primary color, we always see black.

It totally breaks the theme.

**To Reproduce**
1. Update the package.
2. Launch the application

**Expected behavior**
It should enable us to see the primary color as label text color.
**Screenshots**
Before: 
![image](https://user-images.githubusercontent.com/5034215/127646652-7a5ae79f-b069-4456-bf85-1c11df9e81c0.png)

After:
![image](https://user-images.githubusercontent.com/5034215/127646621-b774b2f1-4471-45f6-bc70-8aaeace888e7.png)

**Information (please complete the following information):**
 - Device: Xiaomi Mi 9
 - Platform [e.g. mobile, web]
 - Flutter version: 2.2.3
 - Package version: 2.2.1

**Additional context**
The correct change was made here: https://github.com/NearHuscarl/flutter_login/pull/201/files

**Comment by juliansteenbakker** [comment]
I haven't noticed this so my apologies. We should however have an opt in for changing text colors to primary color because in my use-case, i have the primary color as background of the window, so the text wouldn't be visible.

**Comment by SalahAdDin** [comment]
> I haven't noticed this so my apologies. We should however have an opt in for changing text colors to primary color because in my use-case, i have the primary color as background of the window, so the text wouldn't be visible.

Ah theme, always hard to make. We could use a boolean variable in this case, or calculate it automatically based on the background color...

**Comment by juliansteenbakker** [comment]
Yes indeed it's difficult with many use-cases. You make a good point. We could implement something like this: https://github.com/NearHuscarl/flutter_login/blob/23dcedaffb2becf60c98cea58ea2a53e08c1a7dd/lib/src/widgets/login_card.dart#L353

However this would still not be a solution for people that want to use the 'default' textColor that is showing right now. So we can make a boolean to switch between colored text or not, and if colored, check if background luminance is bright enough for the color that has been provided. What do you think about this?

**Comment by SalahAdDin** [comment]
> Yes indeed it's difficult with many use-cases. You make a good point. We could implement something like this:
> 
> https://github.com/NearHuscarl/flutter_login/blob/23dcedaffb2becf60c98cea58ea2a53e08c1a7dd/lib/src/widgets/login_card.dart#L353
> 
> However this would still not be a solution for people that want to use the 'default' textColor that is showing right now. So we can make a boolean to switch between colored text or not, and if colored, check if background luminance is bright enough for the color that has been provided. What do you think about this?

I think it is a good alternative.
