### ISSUE TITLE
Unable to see "Go Back" button text on any screen.

### ISSUE THREAD

**Issue by babyitachi** [NearHuscarl/flutter_login#214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by juliansteenbakker** [comment]
This is already fixed and will be released later today

**Comment by babyitachi** [comment]
Cool! Thanks 👍

**Comment by juliansteenbakker** [comment]
@babyitachi Did you already try this with v2.2.1?
