### ISSUE TITLE
Animates to new screen wether login is correct or not

### ISSUE THREAD

**Issue by Toernblom** [NearHuscarl/flutter_login#22]
Whatever i put into the email & password textfield i transition into a new screen.

**Comment by NearHuscarl** [comment]
You mean you want to disable email and password validation? if that's what you want then simply return all validations and callbacks to null (return to a string indicate an error with error message is said string)

```dart
    return FlutterLogin(
      onLogin: (_) => Future(null),
      onSignup: (_) => Future(null),
      onRecoverPassword: (_) => Future(null),
     emailValidator: (_) => null,
     passwordValidator: (_) => null,
    );
```

**Comment by jonathanortega2023** [comment]
> You mean you want to disable email and password validation? if that's what you want then simply return all validations and callbacks to null (return a string to indicate an error with error message is said string)
> 
> ```dart
>     return FlutterLogin(
>       onLogin: (_) => Future(null),
>       onSignup: (_) => Future(null),
>       onRecoverPassword: (_) => Future(null),
>      emailValidator: (_) => null,
>      passwordValidator: (_) => null,
>     );
> ```

I think OP was referring to the fact that even if you return null to the callbacks and tap the login button with any acceptable input, the submission animation will play and take you to an empty screen. Is there a way to delay the submission animation until validation completes?
