### ISSUE TITLE
signup screen displayed between sign up card and app screen

### ISSUE THREAD

**Issue by meridorkobi** [NearHuscarl/flutter_login#229]
Start Sign Up  
First card 
Second card
Push SUBMIT
You will see the green success message 
---than you will see second sign up card on the side---
than app

**Comment by meridorkobi** [comment]
![79479](https://user-images.githubusercontent.com/72451004/130512342-dbaeb77e-5980-4309-965d-e6162c3d2228.jpg)

**Comment by SalahAdDin** [comment]
I got this log from debugging:
```shell
[ +309 ms] E/flutter ( 6289): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 455 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
[   +2 ms] E/flutter ( 6289): AnimationController methods should not be used after calling dispose.
[   +1 ms] E/flutter ( 6289): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] E/flutter ( 6289): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] E/flutter ( 6289): #2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:455:7)
[        ] E/flutter ( 6289): #3      _FlutterLoginState.initState.<anonymous closure> (package:flutter_login/flutter_login.dart:388:27)
[        ] E/flutter ( 6289): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
[        ] E/flutter ( 6289): #5      _rootRun (dart:async/zone.dart:1346:47)
[        ] E/flutter ( 6289): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter ( 6289): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
[        ] E/flutter ( 6289): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
[   +2 ms] E/flutter ( 6289): #9      _rootRun (dart:async/zone.dart:1354:13)
[   +3 ms] E/flutter ( 6289): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter ( 6289): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
[        ] E/flutter ( 6289): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] E/flutter ( 6289): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
[        ] E/flutter ( 6289): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
[        ] E/flutter ( 6289): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[        ] E/flutter ( 6289): 

```

**Comment by nyck33** [comment]
@SalahAdDin I am having a similar issue: https://github.com/NearHuscarl/flutter_login/issues/269

**Comment by SalahAdDin** [comment]
@juliansteenbakker was working in a fix for it.

**Comment by nyck33** [comment]
Actually mine went away when I changed the value in the ChangeNotifier as early as possible rather than as late as possible.

**Comment by SalahAdDin** [comment]
> Actually mine went away when I changed the value in the ChangeNotifier as early as possible rather than as late as possible.

which `ChangeNotifer`?

**Comment by nyck33** [comment]
I just made a ChangeNotifier using package provider that gives the loginstatus.

**Comment by SalahAdDin** [comment]
> I just made a ChangeNotifier using package provider that gives the loginstatus.

Well, I would have to review it again.

@juliansteenbakker What do you think about this?

**Comment by nyck33** [comment]
But I was using go_router as well until deep linking did not work so now switched to routemaster.  
Also using AWS Cognito so I do get a sessionValid if valid tokens are in shared preferences but I am using the Changenotifier anyways (actually sorry it's the Riverpod one) so I can access it pretty much anywhere and in block for onLogin, set it to true.

**Comment by nyck33** [comment]
Using routemaster though, I'm back to having this problem.

**Comment by nyck33** [comment]
I am going to rip out this package from my app because it might be causing an issue with my Chrome not being able to run in debug mode.

**Comment by nyck33** [comment]
Actually I don't need to hot restart.  It gets stuck on the first try but on the second try I can only see it very very briefly before it gets to home.

**Comment by nyck33** [comment]
@SalahAdDin  is there an option to turn off the animation?

**Comment by nyck33** [comment]
Actually the example works fine for me so I'm going to copy as much of that into my app as possible.
