### ISSUE TITLE
Can't get it working after installation

### ISSUE THREAD

**Issue by soromamadou** [NearHuscarl/flutter_login#23]
Hi guys,
this looks great. But have an issue juster after installation.
This is the output of the terminal:

`Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:flutter_login/flutter_login.dart';` from project|lib/pages/login/index.dart at 2:1
`

I'm using the beta Channel of Flutter and the plugin installation is done (no error from VSCode) and no error from flutter doctor.
Could you please help me ?

**Comment by soromamadou** [comment]
Seems to me that this is related "transformer_page_view".
I opened new issue on their repository: https://github.com/best-flutter/transformer_page_view/issues/22

**Comment by NearHuscarl** [comment]
Close as resolved in your other issue.
