### ISSUE TITLE
[FEATURE] Can we have option to add "GO BACK" in Signup card?

### ISSUE THREAD

**Issue by meridorkobi** [NearHuscarl/flutter_login#232]
I don't use the confirmation card. 
When the signup process finished with error we don't have option to go back 
and I have to exit the app to start signup again

**Comment by jeffreyliu8** [comment]
there is  go back button, just the color is messed up.

**Comment by tjjv** [comment]
I am not too familiar with signup process, just got one implemented. So I am not sure if this is same issue.

I have problems finding any way to go back from "additional fields". There seems to be no way to go back.

Tried to find something with Flutter inspector, but had no luck there. 
Also tried to click everywhere the invisible button could be to compensate my missing inspector skills. Did not find anything.

**Comment by juliansteenbakker** [comment]
Fixed in #259
