### ISSUE TITLE
Question: how to prepopulate the username/passw fields?

### ISSUE THREAD

**Issue by amigax** [NearHuscarl/flutter_login#237]
Question: how to prepopulate the username/passw fields?
(Also not emails end in .com, can we fix that?)

**Comment by fedepell** [comment]
This feature was added recently in #226 and was merged in `develop` branch. Either you can use that branch for your application or wait when 3.0.0 is released.

**Comment by amigax** [comment]
thanks, when will 3.0.0 be released?

**Comment by fedepell** [comment]
Sincerely I have no idea, maybe @juliansteenbakker that maintains the project has a plan already?

**Comment by fedepell** [comment]
You can now use `3.0.0-beta.2` and have the feature in, so just point to it in your `pubspec.yaml`

**Comment by juliansteenbakker** [comment]
I have finally fixed some bugs so i feel comfortable to release v3.0.0 asap.
