### ISSUE TITLE
goBackButton color theme not matching, text color is white

### ISSUE THREAD

**Issue by jeffreyliu8** [NearHuscarl/flutter_login#239]
![Screen Shot 2021-09-01 at 10 15 26 PM](https://user-images.githubusercontent.com/12398645/131785823-2a9e43e1-95fe-4aff-865b-6ee306c248ac.png)

**Comment by CrayTexas2018** [comment]
Running into this issue as well.

**Comment by yogithesymbian** [comment]
i have solved by `switchAuthTextColor: kPrimaryColor,` in flutter login 2.2.1

**Comment by juliansteenbakker** [comment]
This is fixed in v3.0.0 and will be released asap.
