### ISSUE TITLE
state: _DashboardScreenState#58ebc(ticker inactive)): Bad state: No element

### ISSUE THREAD

**Issue by yogithesymbian** [NearHuscarl/flutter_login#244]
**Describe the bug**
i just copy all dart on example and running on normaly, but i dunno why now if i test login and direct to dashboard the error is came.

**To Reproduce**
1. Click on login
2. Thee error is come

**Expected behavior**
normal as dashboard screen with grid button

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following StateError was thrown building DashboardScreen(dirty, dependencies: [_EffectiveTickerMode, _InheritedTheme, _ModalScopeStatus, _LocalizationsScope-[GlobalKey#f5e5e]], state: _DashboardScreenState#58ebc(ticker inactive)):
Bad state: No element
```

**Comment by juliansteenbakker** [comment]
Please try again with version 3.0.0 and comment if the issue still persists.

**Comment by xuniluser** [comment]
The issue still persists, even with version 4.2.1
