### ISSUE TITLE
[FEATURE] Edit sign up button color and remove card 

### ISSUE THREAD

**Issue by ngocanhnckh** [NearHuscarl/flutter_login#245]
**Is your feature request related to a problem? Please describe.**
I cannot edit the Signup button text colour it keeps being the accent colour and I cannot remove the card in the login
**Describe the solution you'd like**
I want option for changing the Signup button's color and option to disable login card background, thank you!
**Additional context**

**Comment by deliqs** [comment]
I'd love to customize the sign up button, with my preferred design it's a ghost button..

**Comment by juliansteenbakker** [comment]
This is fixed in v3.0.0 and will be released asap
