### ISSUE TITLE
No way back to Login after successful password recovery 

### ISSUE THREAD

**Issue by haukeolf** [NearHuscarl/flutter_login#246]
**Describe the bug**
After successfully requesting a new password, the plugin should navigate back to the login form. Currently the password recovery form stays on screen and there is no possibility to navigate back to the login. The user has to restart the app manually.

**To Reproduce**
1. Go to 'Forgot password'
2. Enter a valid Mail
2. Click on 'Recover'
4. See bug

**Expected behavior**
After successful password recovery the plugin should automatically navigate back to the login form or at least offer a "back" button.

**Screenshots**
<img width="540" alt="Bildschirmfoto 2021-09-10 um 13 00 58" src="https://user-images.githubusercontent.com/44479562/132844283-e5828a23-b6d0-478d-8746-cce1a979caf9.png">

**Comment by fouzan25** [comment]
use switchAuthTextColor: inside theme: LoginTheme

**Comment by haukeolf** [comment]
Thanks a lot, @fouzan25 
That really helped :-)
I'm closing this issue.
