### ISSUE TITLE
LoginUserType Name not working

### ISSUE THREAD

**Issue by jjassobarba** [NearHuscarl/flutter_login#248]
When changing from email to name the loginusertype, the email field and validations are never changed.

**Comment by JacoFourie** [comment]
It seems to me that setting the LoginUserType does not change the lables. It sets up the keyboard. 
You have to use 

            messages: LoginMessages(
            userHint: 'Username' 

to updat ethe lables and set the error in the validator callback.

**userValidator: (value) {
            if (value!.isEmpty) {
              return 'Please enter a username';
            }
            return null;
          },**

**Comment by jjassobarba** [comment]
Yeah I did that and it worked, looks like I misunderstood the documentation. Thanks for the help I am closing the issue.
