### ISSUE TITLE
The successful login animation sometimes gets stuck.

### ISSUE THREAD

**Issue by JacoFourie** [NearHuscarl/flutter_login#249]
**Describe the bug**
Sometime when a the onlogon call back returns null the animation will start and then stop dead staying at the username / password fields.

**Expected behavior**
Complete the animation and move to the screen stated in the afteranimation callback.

**Screenshots**

**Information (please complete the following information):**
 - iPhone 12 and Android simulator
 - Platform mobile
 - Flutter version: 2.5
 - Package version 2.2.1

**Comment by juliansteenbakker** [comment]
This is fixed in v3.0.0 and #273 and will be released asap.
