### ISSUE TITLE
prefixStyle & suffixStyle not work to change icon colors or icon

### ISSUE THREAD

**Issue by yogithesymbian** [NearHuscarl/flutter_login#250]
yaml
```
flutter_login: ^2.2.1
```

i can't change icon color or icon for email, password or eye
```
inputTheme: InputDecorationTheme(
 prefixStyle: TextStyle(
                    color: kPrimaryColor,
                    backgroundColor: kPrimaryColor,
                  ),
                  suffixStyle: TextStyle(
                    color: kPrimaryColor,
                    backgroundColor: kPrimaryColor,
                  ),
)
```
anyone have tricks ?

**Comment by yogithesymbian** [comment]
ah sorry my wrong code

**Comment by Spiderbezno** [comment]
Is this resolved? in v.3.1.0, I can't changed? what is the correct way to change the color of icons in prefix and suffix??

**Comment by Spiderbezno** [comment]
Is this resolved? in v.3.1.0, I can't change it? what is the correct way to change the color of icons in prefix and suffix??

**Comment by Spiderbezno** [comment]
I use these attributes, but the icon does not change, 
prefixIconColor: Colors.yellow,
suffixIconColor: Colors.yellow,
