### ISSUE TITLE
additionalSignupFields property cannot be null to Recover Password

### ISSUE THREAD

**Issue by gitumar** [NearHuscarl/flutter_login#267]
**Describe the bug**
Cannot comment the `additionalSignupFields` property in `FlutterLogin` and go through the Forgot Password process because error is thrown in _auth_card.dart_ line 356 `throw StateError('The additional fields List is null');`

**To Reproduce**
Comment out the `additionalSignupFields` property in `FlutterLogin` and go through the _Forgot Password_ process. Enter email address _dribbble@gmail.com_ if using the example code and click recover and error will throw. If error doesn't throw there try to press back button and then error will throw.

**Expected behavior**
Ability to go through password recovery process without additional signup fields needed in `FlutterLogin`

**Information (please complete the following information):**
 - Device: Android Emulator
 - Platform Emulator
 - Flutter version: 2.5
 - Package version: flutter_login: ^3.0.0-beta.2

**Comment by juliansteenbakker** [comment]
Thanks for reporting, this will be fixed in #273
