### ISSUE TITLE
Tabulation add a space in the email field

### ISSUE THREAD

**Issue by QuentinSc** [NearHuscarl/flutter_login#27]
Hello,

Very good work !

I'm trying to implement it in my project.
Often I test my forms with physical keyboard and I'm facing a bug
Test Login on Android Emulator : 

1. Clic on email field
2. Fill the email field
3. Press "TAB" Key
=> A space is added at the end of the mail

**Comment by NearHuscarl** [comment]
Not sure if it's the same but I couldn't reproduce it on Flutter Web. Can you try the latest version again and on Flutter Web?

**Comment by QuentinSc** [comment]
Hello,

My issue is on Flutter Android with physical keyboard.
Works great on Flutter Web :)

**Comment by TafadzwaD** [comment]
@QuentinSc To get rid of the whitespace created by the tab perform a trim on the email variable.  

emailvariable.trim( ) will remove the trailing space created by Tab.

**Comment by MostHated** [comment]
I am getting this on a desktop build. If I hit tab, it adds a character to the end, but then after entering the password, if I hit enter, it adds another character at the end of the password just before it submits, causing the password to be incorrect.

**Comment by TafadzwaD** [comment]
@MostHated yes it should work..

**Comment by MostHated** [comment]
Unfortunately, that didn't work, but I was able to get it working just how it should by adding into AnimatedTextFormField as well as AnimatedPasswordTextFormField this:

```dart
 final List<TextInputFormatter> formatter; 
```

Then in this:
```dart
Widget textField = TextFormField,
```
 I added:
```dart
inputFormatters: widget.formatter, 
```

Then under _buildNameField():
```dart
      formatter: [
        WhitelistingTextInputFormatter(RegExp(r"([a-zA-Z0-9\-\._@])")),
        BlacklistingTextInputFormatter(RegExp(r"[\r\t+]")),
      ],
```

_buildPasswordField() and _buildConfirmPasswordField()
```dart
      formatter: [
        BlacklistingTextInputFormatter(new RegExp('[\\\r\t+ ]')),
        LengthLimitingTextInputFormatter(20),
      ],
```

**Comment by TafadzwaD** [comment]
@MostHated . So will you explicitly inform users that passwords can not contain whitespace? There are cases where Tabs and Space can be part of a user's password

**Comment by MostHated** [comment]
I have never seen someone use or allow tab as part of a password for a desktop application, but I can just remove the space from the blacklist. I have noticed that the extra character being added to the text box wasn't a space anyways. I would much rather disallow a few characters than have people enter their passwords and it is never correct and constantly fails. So far this way is the only one that works, and minus it not allowing a space in the password ( which again, it can easily just be removed from the regex), it works perfectly for my needs.

**Comment by TafadzwaD** [comment]
@MostHated ok buddie.. If it suits your needs that's the way to go.. Happy coding😎😎
