### ISSUE TITLE
[FEATURE] hideSignUpButton please bring it back 

### ISSUE THREAD

**Issue by nyck33** [NearHuscarl/flutter_login#276]
I just upgraded to 3.0.0 from 2.2.1 because of the animation fixes and now find this button is gone.  Is there any way to bring it back or do I have to use a local cloned copy and edit your source code to not show this button?  In which case, would it be possible for you to point out where?  It's a great feature to have for say an admin dashboard app where I don't want anybody to sign up for the app through a GUI.

**Comment by juliansteenbakker** [comment]
Please see the changelog of version 3.0.0: 
> * Instead of hideSignUpButton, you can now set onSignup parameter to null (or just leave it out) in order to hide the signup button.
https://github.com/NearHuscarl/flutter_login/blob/master/CHANGELOG.md#300-beta2
