### ISSUE TITLE
WEB : Login Text not center

### ISSUE THREAD

**Issue by QuentinSc** [NearHuscarl/flutter_login#28]
Hello,

Flutter : 1.12.13+6
Env : Chrome

![image](https://user-images.githubusercontent.com/16439299/71909281-f92f9f00-316f-11ea-90f9-a6a0c2fa82ce.png)

**Comment by doc-rj** [comment]
@QuentinSc This looks like a duplicate of #7 - I think there is a workaround in there.

**Comment by QuentinSc** [comment]
Oups you're right sorry. But no real workaround :(

**Comment by NearHuscarl** [comment]
Close as duplicated to #7
