### ISSUE TITLE
3.0.0 incompatible with latest firebase

### ISSUE THREAD

**Issue by nyck33** [NearHuscarl/flutter_login#287]
Following this: https://firebase.flutter.dev/docs/auth/overview/

I get:

![image](https://user-images.githubusercontent.com/25189545/142958895-97d9d9e7-2b7b-4cdb-9221-bb7679f7aa49.png)

**Comment by nyck33** [comment]
Resolved sot of with any for firebase in pubspce.yaml

**Comment by juliansteenbakker** [comment]
firebase_core is currently at ^1.10.0. Please update firebase_core to the latest version.

**Comment by nyck33** [comment]
Really?  They had that in the firebase documentation so I just copied it.
