### ISSUE TITLE
Unhandled Exception:  AnimationController methods should not be used after calling dispose.

### ISSUE THREAD

**Issue by wo4haoren** [NearHuscarl/flutter_login#297]
**When login with a valid account  everything is ok. But  logout then login with an invalid account,  got this exception:**

E/flutter (30559): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 488 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
package:flutter/…/animation/animation_controller.dart:1
E/flutter (30559): AnimationController methods should not be used after calling dispose.
E/flutter (30559): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (30559): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (30559): #2      AnimationController.reverse
package:flutter/…/animation/animation_controller.dart:488
E/flutter (30559): #3      _LoginCardState._submit
package:flutter_login/…/cards/login_card.dart:193
E/flutter (30559): <asynchronous suspension>
E/flutter (30559):
W/System  (30559): A resource failed to call release.

**To Reproduce**
1. Login with a valid account.
2. Logout
3. Try to login with an invalid account

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Device:  android emulator & android phone
 - Platform android
 - Flutter version: 
 - Package version  

**Additional context**

**Comment by wo4haoren** [comment]
Solved  by adding this `    if (_submitController.toStringDetails().contains('DISPOSED')) {
      return true;
    }`
    before `await _submitController.reverse();` in login_card.dart line 188.

**Comment by Ben1980** [comment]
I face the same error. Is this something coming soon in a bugfix?

**Comment by Ben1980** [comment]
Seems to be fixed by #383.
