### ISSUE TITLE
username field type 

### ISSUE THREAD

**Issue by presercomp** [NearHuscarl/flutter_login#30]
is possible change validation type for username field?. Now only allow a email address, but, if i need login with a user name, or number id user?

**Comment by NearHuscarl** [comment]
You can change the label and validation of the email `TextField` to suit your need. I may change `emailValidator` parameter to a more generic name like `nameValidator` in the future to make it not imply that this login only support email type.

```dart
 return FlutterLogin(
      messages: LoginMessages(
        usernameHint: 'Your real name',
      ),
      emailValidator: (value) {
        // your name validation logic
      },
      ...
    );
```
