### ISSUE TITLE
dependency failed if font_awesome_flutter ^10.0.0 is used

### ISSUE THREAD

**Issue by jvegaseg** [NearHuscarl/flutter_login#314]
Running "flutter pub get" in XXXX...                        
Because flutter_login 3.2.0 depends on font_awesome_flutter ^9.1.0 and no versions of flutter_login match >3.2.0 <4.0.0, flutter_login ^3.2.0 requires font_awesome_flutter ^9.1.0.
So, because XXXX depends on both font_awesome_flutter ^10.0.0 and flutter_login ^3.2.0, version solving failed.
pub get failed (1; So, because XXXX depends on both font_awesome_flutter ^10.0.0 and flutter_login ^3.2.0, version solving failed.)

Any clue to solve this dependency issue?

**Comment by evanzhoe** [comment]
Agree that a simple update can be done here so that we can use the latest font awesome flutter package.

**Comment by juliansteenbakker** [comment]
This upgrade is blocked by https://pub.dev/packages/flutter_signin_button not using v10 but v9.
