### ISSUE TITLE
How add Facebook login button ?

### ISSUE THREAD

**Issue by Mike4ftv** [NearHuscarl/flutter_login#32]
Hello,

This is a Great login screen 👍.
I would like add, on bottom of screen, the Facebook login button.
Is is possible ? 
I am new in Flutter Dev and I am not sure it is possible to add another widget or Flat button in the screen...

Thanks

**Comment by NearHuscarl** [comment]
Sorry I don't have plan to add social media buttons. I may accept PR for if it's good enough. But here is how I would do it

```dart

    return Stack(
      alignment: Alignment.center,
      children: <Widget>[
        FlutterLogin(...),
        Positioned(
          bottom: 0,
          child: Row(
            children: <Widget>[
              FlatButton(
                child: Text('Facebook'),
                onPressed: () {},
              ),
              FlatButton(
                child: Text('Twitter'),
                onPressed: () {},
              ),
              FlatButton(
                child: Text('Discord'),
                onPressed: () {},
              ),
            ],
          ),
        )
      ],
    );

```

**Comment by psygo** [comment]
@NearHuscarl, it would be sad not to have the maintainer's support of social media sign-in methods as they are so common and mandatory in most apps nowadays.
