### ISSUE TITLE
[FEATURE] upgrade to flutter 3.0

### ISSUE THREAD

**Issue by guchengxi1994** [NearHuscarl/flutter_login#324]
WidgetsBinding.instance!.addPostFrameCallback 'WidgetsBinding' which excludes null

**Comment by AmanMasipeddi** [comment]
I am getting this issue as well.

**Comment by AmanMasipeddi** [comment]
This issue is occuring due to the another_flushbar package which is being used in this plugin. another_flushbar released a new version update 1.10.29. Maybe updating to that version would fix this issue.

**Comment by luca-colazzo** [comment]
it's used in `flutter_login-4.0.0-beta.1/lib/src/widgets/animated_text.dart:57:20` too

**Comment by bulanni00** [comment]
快点更新呀

**Comment by bulanni00** [comment]
This can temporarily solve the flutter 3.0 problem
pubspec.yaml replace  flutter_login: 3.2.0
flutter_login:
      git:
        url: https://github.com/bulanni00/flutter_login.git

**Comment by luca-colazzo** [comment]
or just edit locally the file and remove the ! where reported

**Comment by juliansteenbakker** [comment]
Sorry for the delay, Please upgrade to v4.0.0
