### ISSUE TITLE
Getting null-aware warning on console.

### ISSUE THREAD

**Issue by rvndsngwn** [NearHuscarl/flutter_login#331]
**Describe the bug**
Getting null-aware warning on console.

**To Reproduce**
1. Go to terminal
2. Run flutter command `flutter run`
3. See warning

**Expected behavior**
There should have been no warning on the console.

**Screenshots**
![Screenshot 2022-06-13 at 12 50 56 AM copy](https://user-images.githubusercontent.com/59143934/173250300-2e4eeb9e-7c5c-4612-ae96-ac18588fba24.jpg)

**Information (please complete the following information):**
 - Device: iPhone 13
 - Platform mobile
 - Flutter version: 3.0.2
 - Package version 3.2.0

**Additional context**

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_login-3.2.0/lib/src/widgets/animated_text.dart:57:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
```

**Comment by juliansteenbakker** [comment]
Please upgrade to v4.0.0
