### ISSUE TITLE
Input fields not there on release.

### ISSUE THREAD

**Issue by walteronoh** [NearHuscarl/flutter_login#339]
**Describe the bug**
Input fields and other widgets not there after running 'flutter build apk' but on debug 'flutter run', they are there.

**To Reproduce**
1. git clone https://github.com/NearHuscarl/flutter_login.git
2. cd flutter_login/example
3. Run: flutter build apk
4. cd build/app/outputs/flutter-apk/app-release.apk.
5. Copy the apk to your phone and install.

**Expected behavior**
The application should show all the available elements.

**Screenshots**
(Release)
![Screenshot_20220715-223759](https://user-images.githubusercontent.com/48877319/179305735-287aa22c-4a5b-40f3-a772-c50e2d07c6a1.jpg)

(Debug)
![Screenshot_20220715-231158](https://user-images.githubusercontent.com/48877319/179306124-86b6943e-0378-48cb-971f-f9c628325fec.jpg)

**Information (please complete the following information):**
 - Device: [Samsung Galaxy A13]
 - Platform [mobile]
 - Flutter version: [3.0.2 ]
 - Package version [1.0.0+1]

**Comment by kenken023** [comment]
I can reproduce this on iPad mini 4 iOS 15.4.1

**Comment by betrri** [comment]
I was able to reproduce this aswell and encountered following issues in the flutter repo 
https://github.com/flutter/flutter/issues/99680

It seems that the non elegant way to solve this is to add delay in the main function.

`void main() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Future.delayed(Duration(milliseconds: 1000));
     // I added 1000 ms, but I guess less than 1000 ms will also work.
    runApp(App());
}`

**Comment by walteronoh** [comment]
> I was able to reproduce this aswell and encountered following issues in the flutter repo [flutter/flutter#99680](https://github.com/flutter/flutter/issues/99680)
> 
> It seems that the non elegant way to solve this is to add delay in the main function.
> 
> ```
> void main() async {
>     WidgetsFlutterBinding.ensureInitialized();
>     await Future.delayed(Duration(milliseconds: 1000));
>      // I added 1000 ms, but I guess less than 1000 ms will also work.
>     runApp(App());
> }
> ```

This fix resolved the issue. Thanks @betrri.
