### ISSUE TITLE
Signup doesn't work in Chrome for Android

### ISSUE THREAD

**Issue by Multiply** [NearHuscarl/flutter_login#34]
(Please note, that this is using Flutter for Web)

When toggling signup mode on, the confirm field shows up correctly.
But when focusing any of the fields be it Email, Password, or Confirm password, it shows, and hides the keyboard instantly, while also disabling the Confirm Password field.
Even when I enable Desktop-mode, it still happens.

This does not happen in the browser. on my laptop.

Please let me know if you need more information on how to debug this.

**Comment by NearHuscarl** [comment]
Package version please?

> This does not happen in the browser. on my laptop.

Sorry I didn't catch it, you said it happened on Flutter Web but not in the browser? Can you elaborate?

**Comment by Multiply** [comment]
Latest version of everything.

Flutter for Web on the browser on an Android phone.
I've not even tried to compile it as a real Android app.

**Comment by ananthpranav** [comment]
I have the same problem. Focusing on any field while on signup mode, changes it back to login.

**Comment by khalifa007** [comment]
I have the same problem. Focusing on any field while on signup mode, changes it back to login.

**Comment by andrewjallenuoft** [comment]
I can confirm that this issue also happens in Android on the latest version of the package, making it impossible for new users to signup. 

Hitting the signup button shows normal behavior at first, but once the user focuses on the confirm password field, it immediately changes focus back to the password field and disables the confirm field. It also swaps back in the login button, and the confirm field loses its rounded corners.

<img width="294" alt="1" src="https://user-images.githubusercontent.com/32487067/73070320-f0e19e80-3ea7-11ea-92a2-4bd7a92aeab7.PNG">
<img width="293" alt="2" src="https://user-images.githubusercontent.com/32487067/73070321-f0e19e80-3ea7-11ea-8f76-3fc262b4c74a.PNG">

**Comment by andrewjallenuoft** [comment]
I've done some further testing, and strangely enough it seems that this issue is not present on the iOS emulator, but is present on both the Android emulator and a physical Android device.

**Comment by NearHuscarl** [comment]
Okay, my bad. I messed up the internal state when refactoring. Should be fixed soon.

**Comment by ananthpranav** [comment]
Use this fork https://github.com/evertonAlvaro/flutter_login until the problem gets resolved.
This one is working for me with extra features. Hide the buttons!

**Comment by NearHuscarl** [comment]
This should be fixed in version `1.0.14`
