### ISSUE TITLE
Update Provider Dependency

### ISSUE THREAD

**Issue by jinyus** [NearHuscarl/flutter_login#35]
I cannot use this package because it has an outdated version of provider as a dependency, Could you update the dependency please?
`Because every version of flutter_login depends on provider ^3.1.0 and flygyfs depends on provider ^4.0.1, flutter_login is forbidden.`

**Comment by khalifa007** [comment]
me to

**Comment by NearHuscarl** [comment]
Fixed in `1.0.13+1`

**Comment by khalifa007** [comment]
Thank you
