### ISSUE TITLE
providerNeedsSignUpCallback doesn't show signup card

### ISSUE THREAD

**Issue by denizbora** [NearHuscarl/flutter_login#353]
I tried providerNeedsSignUpCallback function for google signin. I have a function for user to test that it is registered. 
Future<bool> _checkUser(){
    return UserIsExist(AuthenticationHelper().getUid()).then((result) {
      return result;
      });
  }
Future<bool> UserIsExist(String Uid) async{
  var url = Uri.https('***', '/User/check', {'Uid':Uid});
  var response = await http.get(url);
  var status = response as bool;
  return !status;
}
loginProviders: <LoginProvider>[
                LoginProvider(
                  icon: FontAwesome.google,
                  callback: () async {
                    AuthenticationHelper().signInWithGoogle();
                    return null;
                  },
                  providerNeedsSignUpCallback: _checkUser,
                ),
              ],
It does not enter the function _checkUser

**Comment by shinriyo** [comment]
@denizbora 
Your code is hard to read.
please use Markdown tools.

Do you know it?
<img width="302" alt="Screenshot 2023-12-26 at 23 18 15" src="https://github.com/NearHuscarl/flutter_login/assets/396927/4da28abc-6df5-4ca3-9785-f8b6c4c089a0">
