### ISSUE TITLE
 future<dynamic> is not sutype of type '(LoginData) => Future<String>

### ISSUE THREAD

**Issue by khalifa007** [NearHuscarl/flutter_login#37]
I got error when I load FlutterLogin class
it say 
type '(LoginData)=> future<dynamic> is not sutype of type '(LoginData) => Future<String>

**Comment by NearHuscarl** [comment]
You should convert your returned result into a string in the callback (I assume you were using `onLogin` or `onSignup`). I am closing this issue since I don't think it's about FlutterLogin itself. If you disagree, please reopen and elaborate more.

**Comment by khalifa007** [comment]
Yes you are true I should give string return also future<String> , thank you sir so much you did alot of work and I I appreciate your work :) .
