### ISSUE TITLE
Pixel overflow on Screen rotation

### ISSUE THREAD

**Issue by Abhishek-Khanal** [NearHuscarl/flutter_login#38]
Logo and title doesn't show up in landscape orientation and bottom overflows by 20 pixel. Also height and width of logo is not customizable

**Comment by juliansteenbakker** [comment]
Can you please try again with version 1.0.15.

**Comment by sahillakhe** [comment]
I have this same error with version 3.1.0. Did anyone find a resolution to it?

**Comment by khjhs101198** [comment]
same here
