### ISSUE TITLE
Stripping whitespaces from email and password

### ISSUE THREAD

**Issue by Quving** [NearHuscarl/flutter_login#4]
Hello buddy!
First of all, thanks a lot for sharing your login screen :heart:  I really enjoy that and I am using it for my app.

I would like to suggest to **strip the white spaces** before putting them into LoginData object? Sometimes I accidently hit a whitespace and wonder why it does not work! :)

Thanks a lot!

**Comment by NearHuscarl** [comment]
You can add your own stripping logic inside `onLogin`, `onSignup` or `onRecoverPassword` callback before processing the data. Is there anything else I am missing here?
