### ISSUE TITLE
Need to trigger the login buttun twice - Firebase Auth

### ISSUE THREAD

**Issue by JulienT-FL** [NearHuscarl/flutter_login#40]
I need to trigger the button to login twice in order to go to my next screen. First an animation is triggered and my logo disapear. Then after the second hit, the onSubmitAnimationCompleted is called and I am going to my Routing behavior.

Here are some screenshots : The first one if before the first click, and the second one just after it. I need to click again on the button to log-in.

![Screenshot_20200128-133949](https://user-images.githubusercontent.com/57756971/73265505-61086100-41d5-11ea-9a09-e62cefacbeee.jpg)
![Screenshot_20200128-134004](https://user-images.githubusercontent.com/57756971/73265519-6665ab80-41d5-11ea-9b5a-e95fb4ae3e74.jpg)

-Expected behavior :
Only one click needed to go the the onSubmitAnimationCompleted.

Information (please complete the following information):
 - Device: OnePlus 7 pro
 - Platform: Android
 - Flutter version: 1.13.5
 - Package version: 1.0.13

Here is the sourceCode of my LoginPage : 

```
class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  @override
  void initState() {
    super.initState();
    _handleStartScreen();
  }

  // Si le user est deja logué, on redirige vers la page de dashboard
  Future<void> _handleStartScreen() async {
    final authentService = Provider.of<AuthentService>(context, listen: false);
    if (await authentService.isLoggedIn()) {
      Navigator.pushReplacementNamed(context, Router.dashboardRoute);
    }
  }

  @override
  Widget build(BuildContext context) {
    final authentService = Provider.of<AuthentService>(context);
    final compteUtilisateurService = Provider.of<CompteUtilisateurService>(context);

    return FlutterLogin(
      title: 'Nounou gestion',
      logo: 'assets/images/logo-sans-texte.png',
      onLogin: authentService.signIn,
      onSignup: authentService.signUp,
      onRecoverPassword: authentService.recoverPassword,
      showDebugButtons: false,
      onSubmitAnimationCompleted: () async {
        CompteUtilisateur infos = await compteUtilisateurService.getCompteUtilisateur(authentService.getIdUtilisateur());
        // Pas encore renseigné les infos personelles, on le redirige donc le bon écran.
        if (infos.id.isEmpty) {
          Navigator.pushReplacementNamed(context, Router.infosPersosRoute, arguments: CompteUtilisateur());
        } else {
          Navigator.pushReplacementNamed(context, Router.dashboardRoute);
        }
      },
      messages: LoginMessages(
        usernameHint: 'Mail utilisateur',
        passwordHint: 'Mot de passe',
        confirmPasswordHint: 'Confirmation mot de passe',
        loginButton: 'SE CONNECTER',
        signupButton: 'S\'INSCRIRE',
        forgotPasswordButton: 'Mot de passe oublié?',
        recoverPasswordButton: 'Aidez-moi',
        goBackButton: 'Retour',
        confirmPasswordError: 'Les deux mots de passe ne sont pas identiques!',
        recoverPasswordDescription: 'Un lien pour récupérer votre mot de passe va vous être envoyé par email.',
        recoverPasswordSuccess: 'Email de récupération du mot de passe envoyé.',
      ),
    );
  }
}
```

Is it because i don't have any Hero in my other screens after loggedIn ?

Thank you.

**Comment by acalejos** [comment]
Did you ever figure this out? I'm currently facing something similar using Firebase, except mine just makes the logo disappear then doesn't change pages even after 2 clicks of the Login button.

**Comment by margaritageleta** [comment]
Any news? I am facing the same issue....

**Comment by JulienT-FL** [comment]
Unfortunately no ... I just delete this lib and made a login screen by myself because of this bug.

**Comment by MostHated** [comment]
I started having this issue now as well. I was using one Firebase library and moved to another and now I have to click twice, which doesn't quite make sense. I believe I removed the code for the Hero text though, as well. I might check if putting it back fixes it. I suppose it might make sense that if it is trying to perform a specific set of actions in a row and one of them is missing, it might get caught at that part, but not sure why submitting again would cause it to work. 

Though I did just now notice that if I submit it, move my main navigation tab to another screen, then come back to my login tab, it then does the animation, as if it was hung up, then coming back allowed it to work. Though, doing that causes the text and boxes to remain on the screen for some reason.

I put some log messages into the onSubmitCompleted() callback, as well as the _forwardChangeRouteAnimation() function that it calls, which all fired off, which should then call widget.onSubmitCompleted(), which goes up to the parent FlutterLogin class and should call the final onSubmitAnimationCompleted() but it never makes it into there.

Hitting the debug rows ```authCardKey.currentState.runChangeRouteAnimation()``` manually works every time, so I tried to see if I could use that to force the animation by calling it with an event once Firebase reported back that the login was completed successfully, but that didn't quite work out either. It seems to have the same end result.

**Comment by MostHated** [comment]
Just an update to this. I went through and made some adjustments to some of my await methods to my Firebase auth calls and it fixed the need to click it twice, but it's still showing the text and boxes and such when doing the route transition animation, instead of clearing the background out. 

If you are having an issue with needing to click twice, check your awaits for the login, make some adjustments, might end up helping you, too.

**Comment by vptcnt** [comment]
just add in your signIn function :
await Future.delayed(Duration(seconds: 2));

**Comment by MostHated** [comment]
I mean.. it might work, but that sounds like a terrible bandaid to try and apply to async methods. It pretty much defeats the purpose of using async/await.

**Comment by vptcnt** [comment]
I think you need this delay to let it finishing the animation.

**Comment by MostHated** [comment]
You **should** not need to, from what I can tell because the animations are all run in a similar manner to this: ```_forwardChangeRouteAnimation().then((_) => widget.onSubmitCompleted());```. 

Unless something gets changed on your end while messing around with things, the normal flow of events is set up to begin the animation sequence once the login has returned with no error within _LoginCard, which calls the initial widget.onSubmitCompleted() callback, which then moves up the call stack to AuthCardState, which has the snippet above which starts the animation sequence. 

So, if the transition animation has started, it's because either the login has already completed and came back with no error, or it didn't get awaited and the function kept going and started it before the login came back with it's actual result.

**Comment by MostHated** [comment]
Nevermind, I think I see what you are saying now. You meant that the act of logging in and returning was happening too fast, so you needed to give the animation that occurred before the login actually began, but after you pressed the button, time to finish before it starts the route transition animation?

**Comment by vptcnt** [comment]
Indeed. It's the idea.

**Comment by MostHated** [comment]
To make it so that it was not always just an extra two seconds tacked on in addition to whatever the actual login time ended up being, I tested out starting a StopWatch() at the beginning of my login and had a fixed minimum Duration(milliseconds: 2000) and when the login completed, I checked the stopwatches elapsed time against the minimum. If the ET was less than the minimum, use the difference as the duration of the delay, otherwise, just continue.

```
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ Minimum: 2000 | Login ET: 290 | Delay Duration: : 1710
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by FrankSD** [comment]
Any update  on this?i am facing the same issue

**Comment by MaddinMade** [comment]
I have the same issue but without using Firebase
