### ISSUE TITLE
Add biometric authentication support

### ISSUE THREAD

**Issue by feliwir** [NearHuscarl/flutter_login#41]
It would be cool if this plugin allowed login through biometric authentication. So after the first login the user password could be stored inside [biometric_storage](https://pub.dev/packages/biometric_storage) and reused for later logins. 

It should be configurable wether or not that feature is enabled. If interested i could attempt doing a PR for this.

**Comment by juliansteenbakker** [comment]
For now this is out of scope for this project. The package you linked requires a high Android minSDK (23) and this is not favourable for this package. Also I think it adds a lot of complexity, while this packages aims for an easy and simple login solution. I'm closing this for now. Feel free to comment if you think differently.
