### ISSUE TITLE
LoginScreen disappears once loaded.

### ISSUE THREAD

**Issue by jlentijo** [NearHuscarl/flutter_login#42]
**Describe the bug**
LoginScreen disappears once loaded.

**To Reproduce**
1. Clone master branch.
2. Open flutter_login/example/lib/login_screen.dart
3. Set `showDebugButtons: false` at line 172.
4. Run and Debug (F5).
3. See error...

**Expected behavior**
Not disappear...

**Screenshots**
![error_login](https://user-images.githubusercontent.com/1142572/74335514-b11e2080-4d9c-11ea-8644-8d365b93cfb8.gif)

**Information (please complete the following information):**
 - IDE: Visual Studio Code
 - Device: Pixel 3A XL API 29 (Emulator on MacOS)
 - Platform: Mobile
 - Flutter version: 1.12.13+hotfix.7
 - Package version: 1.0.14

**Comment by jerem17** [comment]
I have the same thing on NEXUS 5X API 29 simulator, but it works very well on iPhone!

**Comment by sosaucily** [comment]
I think this might be an issue with the android simulator, i've noticed it as well even after getting through the login experience to the dashboard, but I can't reproduce it on iOS or a real android devicee.

**Comment by android404base** [comment]
I had the same issue also. I fixed it with changing **OpenGL ES API level** from emulator settings.
It was **Renderer maximum** and just change it with **Compatibility**.
From :
<img width="613" alt="Screenshot 2020-05-04 at 12 05 23" src="https://user-images.githubusercontent.com/50708947/80955836-40692c00-8e00-11ea-801b-cd96bbb2dc14.png">

To :
<img width="613" alt="Screenshot 2020-05-04 at 12 05 34" src="https://user-images.githubusercontent.com/50708947/80955844-43641c80-8e00-11ea-9eb0-31b319931a91.png">

Good luck!

**Comment by mehmetyilmaz001** [comment]
Thank you @android404base 👍 this setting saved my life :)
