### ISSUE TITLE
firebase auth

### ISSUE THREAD

**Issue by victorriveraiii** [NearHuscarl/flutter_login#46]
Unable to auth with firebase

firebase auth.createUser doesnt work
firebase auth. get user.id etc....

**Expected behavior**
signup, login, forgot password

**Screenshots**
n/a

**Information (please complete the following information):**
na
**Additional context**
add description in pub to clarify that this login is stored locally

**Comment by victorriveraiii** [comment]
i there a way to use this with firebase?

**Comment by acalejos** [comment]
There's nothing stopping you from using Firebase. Make sure you have Firebase and Cloud Firestore set up in your pubspec.yaml and your gradle configurations. Then you should be able to do something like this in one file:

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_login/flutter_login.dart';

class AuthenticationService with ChangeNotifier {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<String> handleLogin(LoginData lg) async {
    try {
      final user = await _auth.signInWithEmailAndPassword(
          email: lg.name, password: lg.password);
      notifyListeners();
      return user != null ? null : 'Cannot log user in';
    } on AuthException catch (error) {
      notifyListeners();
      return error.message;
    } on Exception catch (error) {
      notifyListeners();
      return error.toString();
    }
  }

}
```

And then pass this as your callback:
```
    return FlutterLogin(
      //other params
      onLogin: Provider.of<AuthenticationService>(context).handleLogin,
    );
```
You could probably use that pattern for all of the callbacks.

**Comment by saranggoel** [comment]
Why is Provider not an identifiable name in my code?
