### ISSUE TITLE
Flushbar problem

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [NearHuscarl/flutter_login#48]
im getting this error:

flutter run error: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.

**Comment by iadr** [comment]
same here, using the github repo as is, i get:


Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

Compiler message:
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/D:/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
  void install() {
       ^
lib/custom_route.dart:21:17: Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
 - 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/navigator.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.
    if(settings.isInitialRoute){
                ^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:281:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^

Compiler message:
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
/D:/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
  void install() {
       ^
lib/custom_route.dart:21:17: Error: The getter 'isInitialRoute' isn't defined for the class 'RouteSettings'.
 - 'RouteSettings' is from 'package:flutter/src/widgets/navigator.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/navigator.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.
    if(settings.isInitialRoute){
                ^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:281:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 840

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by Void1315** [comment]
This is really frustrating. I submitted a PR to fix this bug.  PR:https://github.com/NearHuscarl/flutter_login/pull/51

**Comment by Void1315** [comment]
This error only occurs on the flutter of the beat and master branches. If you have no special requirements, you can switch to the stable version for development.

**Comment by reducedwow** [comment]
```
dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^1.0.14
  intl: ^0.16.1
  flushbar: 1.9.1
```

please check the flushbar version 1.9.1 problem solved for me 
try debug after `flutter clean`

Have a Good Day

**Comment by JCKodel** [comment]
If you don't want to add flushbar as a direct dependency, you can always override it:

```
dependency_overrides:
  flushbar: 1.9.1
```

**Comment by foxmedo** [comment]
same problem i have use this 

dependency_overrides:
  flushbar: 1.9.1
