### ISSUE TITLE
Disable password textfield to start with a capital letter

### ISSUE THREAD

**Issue by Quving** [NearHuscarl/flutter_login#5]
Hello,

I do not know, if it's a OS issue or a flutter one. So, if it's not a flutter one, let me know. 

I'm facing the problem, that everytime I click into the password textfield to enter my password, my  keyboard locks the shift for the capital letter for the first letter. So i have to manually disable it.

Is it a thing that can be set in flutter?

Thanks in advance! :)

**Comment by NearHuscarl** [comment]
I don't have that issue on Android. The default `TextCapitalization` in my `TextField`s are all none (no character is uppercased).
