### ISSUE TITLE
Missing entries on LoginMessages and SVG support

### ISSUE THREAD

**Issue by JCKodel** [NearHuscarl/flutter_login#53]
1) There are two untranslatable texts on `widget_helper.dart`: both shows success and errors toasts with hardcoded titles (Success and Error):

https://github.com/NearHuscarl/flutter_login/blob/823d79f9feaf194e794c89062d06c8617f6af899/lib/src/widget_helper.dart#L12

https://github.com/NearHuscarl/flutter_login/blob/823d79f9feaf194e794c89062d06c8617f6af899/lib/src/widget_helper.dart#L29

Those strings should be on `LoginMessages` class.

---

2) The `logo` property is a String passed to an `Image.asset()`. It would be nice if we had a `Widget logoWidget` property, so we could use, for instance, `SvgImage.asset()` (or really anything else we want as the logo).

**Comment by srkraut** [comment]
do you have any idea how can we add new field like  full name during sign up ?

**Comment by juliansteenbakker** [comment]
The first issue wil be solved in upcoming release #117. The second issue wil be tracked with #33.
