### ISSUE TITLE
Adding new field on sign up 

### ISSUE THREAD

**Issue by srkraut** [NearHuscarl/flutter_login#54]
how can i add new field like first name and last name during sign up ? any code sample

**Comment by junger92** [comment]
how can i add new field like combobox during sign up ?

**Comment by VarunaLakshan** [comment]
how can I add a new field in sign up?

**Comment by mehmetyilmaz001** [comment]
I also need this feature. Signup fields should be customized.

**Comment by JohnBerd** [comment]
Need this too! Any update?

**Comment by everters** [comment]
It would be really nice to add a few more fields that can be enabled/disabled. for example this could be controlled when instantiating login interface. 

what about including a common list of other fields such as: name, surname, phone number and maybe a couple of generic ones for special uses?

**Comment by juliansteenbakker** [comment]
This is a good idea. I do think however the fields should be generic, so that the user can decide how the field is called. I'm thinking about something like this:

```dart
return FlutterLogin(
      signupFields: <LoginField>[
                LoginField(
          icon: Icons.phone,
          title: 'Phone',
          hint: 'Your phone number'
          ),
        LoginField(
            icon: Icons.location_city,
            title: 'City',
            hint: 'Your city'
        ),
      ],
    );
  }
```

We can add the list with `LoginField` to the `LoginData` class so we can pass it back in the `onSignup` and `onLogin` callbacks.

**Comment by everters** [comment]
That would be really awesome. being able to pass a list of LoginField is exactly what would be needed.

Do you already have a PR that can be reviewed?


Thanks for the awesome work!

**Comment by juliansteenbakker** [comment]
> Do you already have a PR that can be reviewed?

Not yet. I have some other work to do before i can work on this so if anyone else want to contribute it would be great.

**Comment by SalahAdDin** [comment]
@juliansteenbakker what's about a way to change the labels? In our project we wanna use **email** instead of **username**, and to avoid adding a new username, changing the label is more than enough.

**Comment by juliansteenbakker** [comment]
@SalahAdDin Thats also a good idea. Can you create a new feature ticket for that?

**Comment by SalahAdDin** [comment]
> @SalahAdDin Thats also a good idea. Can you create a new feature ticket for that?

[Done](https://github.com/NearHuscarl/flutter_login/issues/141).

**Comment by spicylola** [comment]
is there a way we can add custom fields to sign up??

**Comment by jonbhanson** [comment]
Would also love this feature: I need a name field on user signup.  Great package, btw! 👍🏻

**Comment by surister** [comment]
Working on this, adding one extra field looks fine, 3 fields is not viable.. Any ideas?

![image](https://user-images.githubusercontent.com/37985796/114934847-c0827900-9e3a-11eb-8e91-ade8d595467b.png)

**Comment by SalahAdDin** [comment]
@juliansteenbakker what do you think?

**Comment by juliansteenbakker** [comment]
Upon seeing this I think maybe we can make one extra field optional (if this is wanted), but i doubt it would be a good idea to add more fields since it would compromise the look and feel of this package. This is also something that the original developer was against.

PS: i have some other priorities at work right now so i can be late to respond however this will only be the case for this month.

**Comment by surister** [comment]
Another option could be to build a new card like we do in `recover password` when we feed more than 3 sign up fields, as long as we properly document and write examples for this, it might be alright, what do you guys think?

**Comment by SalahAdDin** [comment]
@surister I could be a good solution, it giving a mechanism to inject a custom card with the desired fields as callback to the login.

**Comment by Dorbmon** [comment]
Anything new about this?

**Comment by SalahAdDin** [comment]
It seems @juliansteenbakker is busy these days... so the package got freezed again.

**Comment by karim00005** [comment]
any update??

**Comment by surister** [comment]
I'm kinda waiting for Julian

**Comment by juliansteenbakker** [comment]
> nother option could be to build a new card like we do in `recover password` when we feed more than 3 sign up fields, as long as we properly document and write examples for this, it might be alright, what do you guys think?

This could be possible indeed. This way the 'original' sign-up field would still be available for people that only need that, and other people who want more field can select a 'custom card'.   However, i don't have the time right now to implement this. I am however accepting PR's so if someone wants to realize this, that would be awesome.

**Comment by Dorbmon** [comment]
Still waiting...

**Comment by SalahAdDin** [comment]
@Dorbmon As far as i know @juliansteenbakker is very bussy this days, you could try to make a pull request in order to make his work easier.

**Comment by Dorbmon** [comment]
> @Dorbmon As far as i know @juliansteenbakker is very bussy this days, you could try to make a pull request in order to make his work easier.

https://github.com/NearHuscarl/flutter_login/pull/188
My try...May be a bit ugly.

**Comment by azazadev** [comment]
any new please ?

**Comment by malta895** [comment]
Please take a look at #205, I implemented it in a generic way. It still needs to be improved

**Comment by juliansteenbakker** [comment]
Functionality is merged and released in v3.0.0-beta.1. Please report any problems in new tickets. Thank you all for your patience.

**Comment by pepie** [comment]
Was this removed in 5.0.0?

**Comment by SalahAdDin** [comment]
> Was this removed in 5.0.0?

why do you think that?

**Comment by pepie** [comment]
Sorry, I found the solution. Apparently the extra fields are displayed after the submitting the initial signup field.
