### ISSUE TITLE
Crashes when released on a real ios device when a text field is tapped

### ISSUE THREAD

**Issue by patmuk** [NearHuscarl/flutter_login#55]
**Describe the bug**
App crashes when a text field (user name or password) is tabbed. I guess when the keyboard should be shown.

**To Reproduce**
1. Load the flutter_login widget
2. Click on the field "email" or "password"
3. App crashes

**Expected behavior**
Keyboard should pop up.

**Information (please complete the following information):**
 - Device: iPhone X
 - Platform ios
 - Flutter version: 1.12.13+hotfix.8 (channel stable)
 - Package version: 1.0.14

**Additional context**
Works fine in the simulator, bug happens when compiled in release mode an running on the real device (I distributed it via TestFlight).
Only the theme, logo and company name was changed, login data was taken locally (as in the example).

**Comment by danisev7** [comment]
Hi @patmuk ,

Here the same, but I just hit this exception when I have Break on all exceptionsenabled in VS code.

I think is related with this flutter issue: https://github.com/flutter/flutter/issues/40427

**Comment by juliansteenbakker** [comment]
Can't reproduce this. Please comment if you still have this issue.
