### ISSUE TITLE
How do I add option to sign in with gmail?

### ISSUE THREAD

**Issue by mgmanav91** [NearHuscarl/flutter_login#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by ChesterDenn** [comment]
Hopefully, my patch one will help your problem. https://github.com/ChesterDenn/flutter_login/commit/05bb14a24bcdeaaa7c8d0978002c9a337b1f381a

**Comment by xnio94** [comment]
this [pull request](https://github.com/NearHuscarl/flutter_login/pull/79) should add support to sign in providers like Google and Facebook...

@ChesterDenn i wish i saw your work before making it myself (i think you should have made a pull request to the original repository)

**Comment by juliansteenbakker** [comment]
This is added in #112
