### ISSUE TITLE
[Question] Decrease time before initial login animation begins?

### ISSUE THREAD

**Issue by MostHated** [NearHuscarl/flutter_login#59]
Hello,  
  Does anyone happen to know if there is a way to reduce the amount of time it takes to begin playing the initial login animation? I can't seem to locate where that might be. 

Thanks, 
-MH

**Comment by TafadzwaD** [comment]
@MostHated . Try changing the loadingduration in flutter_login.dart(Fin attached picture)
![LOGIN(TIMER)](https://user-images.githubusercontent.com/28431370/80474138-6ba6d380-8947-11ea-816d-15aef225f498.PNG)

**Comment by MostHated** [comment]
Hey there,  
I appreciate you taking the time to reply. I gave that a try but unfortunately, it wasn't quite what I was after. I am ok with the speed of the animations that happen, there just seems to be what feels like a 4-600ms delay before the animation even starts. If you see below, when I click the update button there seems to be somewhat of a significant delay in which, for a second, it feels like maybe it's not going to load, but then it does. But when I click back to home everything is ready to go right away. 

![https://i.imgur.com/sndje33.gif](https://i.imgur.com/sndje33.gif)


When I changed the value you recommended, that slight delay was still present, but then when it did finally begin the animation just happened faster.

![https://i.imgur.com/qbDN7A6.gif](https://i.imgur.com/qbDN7A6.gif)

I am not quite sure where it is coming from, though.

Thanks,
-MH

**Comment by TafadzwaD** [comment]
@MostHated  . Let me dig deep and see whether i can figure it out and the give you some feedback. If possible kindly share your code associated to Clicking UPDATE as referenced on your gif/pic

**Comment by TafadzwaD** [comment]
I am assuming that it has to do with synchronous code execution.

**Comment by MostHated** [comment]
Sure thing. Here are the primary responsible parties.

Here is where the actual Update button is pressed.
https://github.com/instance-id/searcher_installer/blob/e64838f55dd4abf60f12a6eb96effc8c1931d20b/lib/routes/tab_menu.dart#L227

Which then heads to here:
https://github.com/instance-id/searcher_installer/blob/e64838f55dd4abf60f12a6eb96effc8c1931d20b/lib/routes/tab_menu.dart#L162

The parent also gets the onChanged to handle the PageView change.
https://github.com/instance-id/searcher_installer/blob/e64838f55dd4abf60f12a6eb96effc8c1931d20b/lib/app_home.dart#L84

Thanks again, I really appreciate it.
-MH

**Comment by TafadzwaD** [comment]
@MostHated . I am glad that you finally nailed it!!! 😎😎😎😎 . And thanks for the update on the solution
