### ISSUE TITLE
isInitialRoute deprecated

### ISSUE THREAD

**Issue by TafadzwaD** [NearHuscarl/flutter_login#62]
Thank you for the wonderful   @NearHuscarl 

**Describe the bug**
isInitialRoute is deprecated in newer versions of flutter and is resulting to the following error
` The getter 'isInitialRoute' isn't defined for the class 'RouteSettings' clear and concise description of what the bug is.`

**Flutter Version**
Flutter version 1.17.1

Is there a work around?

**Comment by davidmednikov** [comment]
Same issue here - prevents me from building.

**Comment by evertonAlvaro** [comment]
Hello, I fixed this on my fork. Also add some more features.
https://github.com/evertonAlvaro/flutter_login

**Comment by davidmednikov** [comment]
> Hello, I fixed this on my fork. Also add some more features.
> https://github.com/evertonAlvaro/flutter_login

Looks like a lot of useful changes, but I'm getting errors about the "control-flow-collections" needing to be enabled, and a lot of deprecated packages being used. Thanks for your work though. This package is worth fixing.

**Comment by lcsvcn** [comment]
@evertonAlvaro Did you submit a PR?

**Comment by evertonAlvaro** [comment]
@lcsvcn Yes, it's been a while. I use and like the plugin, so I always try to help when I find a bug.
https://github.com/NearHuscarl/flutter_login/pull/31

**Comment by lcsvcn** [comment]
@evertonAlvaro There is a new maintainer, we may see this PR merged soon.
