### ISSUE TITLE
Title Fonts OpenSans and Pacifico avoiding Image to show

### ISSUE THREAD

**Issue by lcsvcn** [NearHuscarl/flutter_login#66]
Some fonts make the logo image not to be shown.

I have reduced the Title Font at minimum and also reduced the image, it cannot make it work.

Please, I want to use Pacifico at title font, can you guys fix this??

To reproduce this bug:

Set title font to pacifico or to openSans, like this: 
`fontFamily: GoogleFonts.pacifico().fontFamily,`

Run on a mobile device, try to have a logo image and title at the same page and fails.

https://imgur.com/o67Hfrn

**Comment by lcsvcn** [comment]
Add this to your Flutter Login:

`theme: LoginTheme(
              titleStyle: TextStyle(
                fontFamily: GoogleFonts.pacifico().fontFamily,
                fontSize: 24,
              ),
            ),`

**Comment by juliansteenbakker** [comment]
I have tried it with the latest version and can't reproduce this bug. Please comment if you still have problems.
