### ISSUE TITLE
The password must be 8 chara.... not fitting in the line.

### ISSUE THREAD

**Issue by vanshiqa** [NearHuscarl/flutter_login#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by juliansteenbakker** [comment]
You can set this yourself with
```dart
      passwordValidator: (value) {
        if (value.isEmpty) {
          return 'Password is empty';
        }
        return null;
      },
```
