### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by aldisapriansyah** [NearHuscarl/flutter_login#68]
I try run 'flutter pub get'

But I got this error

Error on line 19, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
19 │   flutter_login: ^1.0.14
   │   ^^^^^^^^^^^^^
   ╵
Running "flutter pub get" in flutter_login-master...
pub get failed (65;    ╵)

and this is my dependencies
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.2
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  # flutter_test from sdk depends on quiver 2.0.5
  quiver: ^2.0.5
  flutter_login: ^1.0.14

**Comment by lcsvcn** [comment]
@aldisapriansyah You probably got that error because your **pubspec.yaml** is not well formatted. Could you double check this?

**Wrong Formatting:**
```
dependencies:
  flutter:
    sdk: flutter
    flutter_login: ^1.0.14

```

**Right Formatting:**
```
  flutter:
    sdk: flutter


  flutter_login: ^1.0.14
```

Let me know if that helps you!

**Comment by aldisapriansyah** [comment]
Thanks for the response, actually I've had found the solution a long time ago, but still, thanks for the response
