### ISSUE TITLE
Login in button doesn't appear right on flutter for web

### ISSUE THREAD

**Issue by Jeremywhiteley** [NearHuscarl/flutter_login#7]
The text in the login button for **flutter for the web** isn't positioning right.    This is the only issue I have found when using this with the latest version of Flutter Master Channel.    

<img width="647" alt="Screenshot 2019-11-14 15 13 49" src="https://user-images.githubusercontent.com/1545134/68900576-659e9c80-06f1-11ea-8e0c-aa0b41b561ad.png">

**Comment by Jeremywhiteley** [comment]
If I go into animated_button.dart to line 138 and remove this line, 

`style: theme.textTheme.button,`

It centers it, but the theming is applied correctly.

**Comment by beaniebag** [comment]
I'm getting the same problem.  It's to do with the AnimatedText.  I've noticed that if you click the Signup button the old text position is correct but then it transforms into the new text position which is incorrect.

**Comment by thsieh123** [comment]
I have to work around by removing not only the style but also changing the AnimatedText to Text 

`
     child: Text(
        widget.text
)
`

Of course, it doesn't animated anymore but it's not too bad.

**Comment by krunduev** [comment]
The same

**Comment by NearHuscarl** [comment]
Right now web support is not my highest priority until it becomes more stable. But I will leave the issue here if anyone finds a good way to solve it.

**Comment by NearHuscarl** [comment]
I made a workaround in `1.0.11`. Please try again to see if it works for you

**Comment by QuentinSc** [comment]
Work for me ! Thank you
