### ISSUE TITLE
How to get values from TextFields ,please help

### ISSUE THREAD

**Issue by sohrabonline** [NearHuscarl/flutter_login#70]
How to get values from TextFields ,please help , i want use it but i can not understand

**Comment by Programmer9211** [comment]
Hey Sohrabonline you can get values from Textfield by using this code...


       TextEdittingController _controller = TextEdittingController();

       TextField(
       controller : _controller,
       ),

       RaisedButton(
       onpressed  : () => print(_controller.text)     
       ),

for getting the values from TextField you can use   _controller.text

**Comment by sohrabonline** [comment]
Thank you ❤️
