### ISSUE TITLE
Can I request the possibility to disable the "Register" Button

### ISSUE THREAD

**Issue by von-maurus** [NearHuscarl/flutter_login#72]
Hi!, first, thank you so much for your Widget, it's really cool specialy the animations. I wanted to request adding the possibility to change the state of the elements in the widget. Eg: a boolean value to whether or not showing the buttons, Sign up & Sign In. 

Also, It would be cool adding some more labels or buttons to it. (like google+ or FB sign In).

![image](https://user-images.githubusercontent.com/9019172/88728137-0b1e6280-d0ff-11ea-8c8d-3ae44c8abb7a.png)

**Comment by justinemailone** [comment]
I also need to disable the register button. I noticed the code had the properties `// hideButtonForgotPassword: true,
      // hideButtonSignUp: true,` commented out and they are not implemented.

**Comment by mehmetyilmaz001** [comment]
I also need this feature.

**Comment by kahlil29** [comment]
I too need to hide or disable to register button. 
If not, is there a way to do another action when the register button is pressed? E.g. a popup/dialog with some text.

**Comment by kahlil29** [comment]
I found a workaround/solution at #63

**Comment by juliansteenbakker** [comment]
Duplicate of #19
