### ISSUE TITLE
Login card appears too low with wide margin at the top

### ISSUE THREAD

**Issue by allurefx** [NearHuscarl/flutter_login#74]
**Describe the bug**

**To Reproduce**
1. Create a regular FlutterLogin screen with no title or logo

**Expected behavior**
The login card should appear at the top, but there is a large margin at the top
and the card appears way below and sometimes completely out of view, requiring
a scroll-up to see.

**Screenshots**

**Information (please complete the following information):**
 - All platforms

**Additional context**

**Comment by juliansteenbakker** [comment]
If this issue still exists, can you provide a screenshot of the problem? I'm closing it for now. Please comment if you still have this issue.
