### ISSUE TITLE
Anonymous login

### ISSUE THREAD

**Issue by amazwrlds** [NearHuscarl/flutter_login#76]
**Description of the new feature**
I love you fluttter_login project very much. if you have enough time please add feature to login anonymously. For example "ANONYMOUS" word with link on login screen and attribute for callback into FlutterLogin class. This allow users understand opportunity to login anonymously

**Comment by xnio94** [comment]
you can use this [pull](https://github.com/NearHuscarl/flutter_login/pull/79)   add an ANONYMOUS icon

**Comment by juliansteenbakker** [comment]
This is possible with #79.
