### ISSUE TITLE
Add extra buttons for social media authentication 

### ISSUE THREAD

**Issue by bdevay** [NearHuscarl/flutter_login#82]
Hi,

It's rather a feature request or support request than a bug report.

Is there any way to add extra buttons to the screen? I'm looking for something like the debug animation buttons but I want to customize them to be used for other authentication types like Google, for instance. Actually, my intention is to use your widget with the flutter_signin_button if possible.

**Comment by CharlesCCC** [comment]
@bdevay I have added the support of `child` widget to the login page on my branch and PR to this repo. Hopefully the Author will able to merge. #88

**Comment by bdevay** [comment]
> @bdevay I have added the support of `child` widget to the login page on my branch and PR to this repo. Hopefully the Author will able to merge. #88

Thanks @CharlesCCC . I have found that the Author is already working on it and I pulled the latest version which solved this request. I didn't close the issue only because it's not yet on the master.

**Comment by CharlesCCC** [comment]
@bdevay Glad your issue is resolved, would you please elaborate on how did you solved it ? Because I can't tell from the document on how to integrate with social(3rd party) login.

**Comment by bdevay** [comment]
> @bdevay Glad your issue is resolved, would you please elaborate on how did you solved it ? Because I can't tell from the document on how to integrate with social(3rd party) login.

Sorry, I was wrong. It wasn't the original Author but please check it here: https://github.com/NearHuscarl/flutter_login/pull/79

**Comment by Macacoazul01** [comment]
it will be awesome if this is implemented

**Comment by juliansteenbakker** [comment]
Merged #79.
