### ISSUE TITLE
Customizable Title

### ISSUE THREAD

**Issue by bdevay** [NearHuscarl/flutter_login#83]
Feature request.

Please use Text instead of String for defining Title in FlutterLogin constructor to provide the option for setting a unique text style.
I think it should be a general requirement to be the title customizable since it makes sense to show the company name there which should have a unique style.

**Comment by juliansteenbakker** [comment]
I think this not only applies to Text, but also to some Icons and other elements.

**Comment by juliansteenbakker** [comment]
For title you can use something like: 
```dart
      LoginTheme(
        titleStyle: TextStyle(
          fontSize: 14.0
        )
      ),
```
Or if you want to use Google Fonts
```dart
LoginTheme(
        titleStyle: GoogleFonts.lobster()
      ),
```
