### ISSUE TITLE
Customization of any UI control element

### ISSUE THREAD

**Issue by bdevay** [NearHuscarl/flutter_login#84]
Feature request.

I faced the issue that I need to customize the UI according to my needs and there is no option for it.
Therefore I've started to change the code of your widget itself and I don't like to do it because of the likelihood of hard maintenance effort in the future.
That would be nice to have a much comprehensive UI customization possibility.
BTW, what is your license restrictions regarding modifying your code? Also, can it be used for commercial purposes if it will be the case later on?

**Comment by juliansteenbakker** [comment]
License information can be found here: https://github.com/NearHuscarl/flutter_login/blob/master/LICENSE

As for customising UI elements. This is planned for a future release and will be tracked in #83.
