### ISSUE TITLE
"severity": 8, 	"message": "The getter 'isInitialRoute' isn't defined for the type 'RouteSettings'.\nTry importing the library that defines 'isInitialRoute', correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'."

### ISSUE THREAD

**Issue by luismacalderon** [NearHuscarl/flutter_login#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information (please complete the following information):**
 - Platform [e.g. mobile, web]
 - Flutter version: [e.g. 1.12.13]
 - Package version [e.g. 1.0.0]

**Additional context**

**Comment by AzarouAmine** [comment]
`isInitialRoute` in `RouteSettings` has been deprecated and been changed to `name` instead.
