### ISSUE TITLE
Typedef AuthCallback is not exported

### ISSUE THREAD

**Issue by scopendo** [NearHuscarl/flutter_login#93]
**Describe the bug**
It is not possible to reference the AuthCallback typedef in one's own code as it is not exported by the flutter_login package.  This can be useful when onLogin calls a function that returns the auth callback function, which can be useful to inject the build context when using a stateless widget.

```dart
@override
Widget build(BuildContext context) {
  return FlutterLogin(
    ...
    onLogin: _loginUser(context),
  }
}

AuthCallback _loginUser(BuildContext context) {
  return (LoginData loginData) {
    // Login actions that require the build context, such as to read a provider
  }
}
```

**Additional context**
Of course, it is possible to avoid this by putting such logic directly into the build method, however, that can contribute to code that is harder to follow.

**Comment by juliansteenbakker** [comment]
Why should we? We can get this working without the `AuthCallback` like so:
```dart
@override
Widget build(BuildContext context) {
  return FlutterLogin(
    ...
    onLogin: (loginData) => _onLogin(loginData, context),
  }
}

  Future<String> _onLogin(LoginData loginData, BuildContext context) {
    // Do what you want
    return null;
  }
```

**Comment by scopendo** [comment]
You of course don't have to, it's just odd not to. In the same way that the Flutter team don't have to export VoidCallback or WidgetBuilder, etc.
