### ISSUE TITLE
I don't see any option to change the prefix icon

### ISSUE THREAD

**Issue by sahil-scrobits** [NearHuscarl/flutter_login#94]

**Comment by juliansteenbakker** [comment]
What prefix icon would you like to change? I'm closing this for now since this ticket is 6 months old but feel free to comment if you still want this changed.

**Comment by riyan-datalyca** [comment]
Is it the icon attribute for TextField? Even I was searching to change Icons.account_circle to custom icon for the Email TextField. Is there any way to do this?
