### ISSUE TITLE
new feature : disable alert message

### ISSUE THREAD

**Issue by robertoltrocha** [NearHuscarl/flutter_login#95]
Hi,
Is it possible to disable the all alert message in the bottom screen? success or error ? I would like to create my own messages.
and this messages title is English.

Thanks

**Comment by TafadzwaD** [comment]
@robertoltrocha Yes you can define you own messages .eg `     messages: LoginMessages(
        //   usernameHint: 'Username',
        //   passwordHint: 'Pass',
        //   confirmPasswordHint: 'Confirm',
        //   loginButton: 'LOG IN',
        //   signupButton: 'REGISTER',
        //   forgotPasswordButton: 'Forgot huh?',
        //   recoverPasswordButton: 'HELP ME',
        //   goBackButton: 'GO BACK',
        //   confirmPasswordError: 'Not match!',
        //   recoverPasswordIntro: 'Don\'t feel bad. Happens all the time.',
        //   recoverPasswordDescription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
           recoverPasswordSuccess: 'Email with password recovery steps sent',
        
        // ),
        // theme: LoginTheme(
        //   primaryColor: Colors.teal,
        //   accentColor: Colors.yellow,
        //   errorColor: Colors.deepOrange,
        //   pageColorLight: Colors.indigo.shade300,
        //   pageColorDark: Colors.indigo.shade500,
        //   titleStyle: TextStyle(
        //     color: Colors.greenAccent,
        //     fontFamily: 'Quicksand',
        //     letterSpacing: 4,
        //   ),
        //   // beforeHeroFontSize: 50,
        //   // afterHeroFontSize: 20,
        //   bodyStyle: TextStyle(
        //     fontStyle: FontStyle.italic,
        //     decoration: TextDecoration.underline,
        //   ),
        //   textFieldStyle: TextStyle(
        //     color: Colors.orange,
        //     shadows: [Shadow(color: Colors.yellow, blurRadius: 2)],
        //   ),
        //   buttonStyle: TextStyle(
        //     fontWeight: FontWeight.w800,
        //     color: Colors.yellow,
        //   ),
        //   cardTheme: CardTheme(
        //     color: Colors.yellow.shade100,
        //     elevation: 5,
        //     margin: EdgeInsets.only(top: 15),
        //     shape: ContinuousRectangleBorder(
        //         borderRadius: BorderRadius.circular(100.0)),
        //   ),
        //   inputTheme: InputDecorationTheme(
        //     filled: true,
        //     fillColor: Colors.purple.withOpacity(.1),
        //     contentPadding: EdgeInsets.zero,
        //     errorStyle: TextStyle(
        //       backgroundColor: Colors.orange,
        //       color: Colors.white,
        //     ),
        //     labelStyle: TextStyle(fontSize: 12),
        //     enabledBorder: UnderlineInputBorder(
        //       borderSide: BorderSide(color: Colors.blue.shade700, width: 4),
        //       borderRadius: inputBorder,
        //     ),
        //     focusedBorder: UnderlineInputBorder(
        //       borderSide: BorderSide(color: Colors.blue.shade400, width: 5),
        //       borderRadius: inputBorder,
        //     ),
        //     errorBorder: UnderlineInputBorder(
        //       borderSide: BorderSide(color: Colors.red.shade700, width: 7),
        //       borderRadius: inputBorder,
        //     ),
        //     focusedErrorBorder: UnderlineInputBorder(
        //       borderSide: BorderSide(color: Colors.red.shade400, width: 8),
        //       borderRadius: inputBorder,
        //     ),
        //     disabledBorder: UnderlineInputBorder(
        //       borderSide: BorderSide(color: Colors.grey, width: 5),
        //       borderRadius: inputBorder,
        //     ),
        //   ),
        //   buttonTheme: LoginButtonTheme(
        //     splashColor: Colors.purple,
        //     backgroundColor: Colors.pinkAccent,
        //     highlightColor: Colors.lightGreen,
        //     elevation: 9.0,
        //     highlightElevation: 6.0,
        //     shape: BeveledRectangleBorder(
        //       borderRadius: BorderRadius.circular(10),
        //     ),
        //     // shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
        //     // shape: CircleBorder(side: BorderSide(color: Colors.green)),
        //     // shape: ContinuousRectangleBorder(borderRadius: BorderRadius.circular(55.0)),
        //   ),
         ),`

**Comment by robertoltrocha** [comment]
Hi,
I saw that I had the translation options, but I didn't see the option to translate the title of this message and disable this message, I would like to put my own message in the top.
**"Success" is in english.**
![caputre2](https://user-images.githubusercontent.com/30963205/101296405-1c405400-3802-11eb-8ef7-d5ef9872a367.jpg)

**Comment by winds1983** [comment]
Same questions.

**Comment by juliansteenbakker** [comment]
This is implemented with #117 and will be released in the next version.
