### ISSUE TITLE
how can i initialize email and password?

### ISSUE THREAD

**Issue by robertoltrocha** [NearHuscarl/flutter_login#99]
Hi,
Maybe I'm asking an obvious question, how do I initialize the email and password variables? I didn't find the controllers.
I want to start these variables with the password and email saved on the mobile when the login screen open.

thanks

**Comment by OmarYehiaDev** [comment]
You can achieve this approach without using these credentials. I'd achieved it in my app by using SharedPreferences package to save locally if the user is logged in or not. Then, a simple if statement can drive the flow of your app easily

**Comment by robertoltrocha** [comment]
HI @OmarYehiaDev,

I saved the credentials with by using SharedPreferences package to save locally if the user is logged. But I would like to show the email and password saved in the fields.

thanks

**Comment by OmarYehiaDev** [comment]
Oh I got you. If you wanna show 'em I think it will be necessary to access the TextControllers of the fields. I think you can try to show the user a message that tells him to check the connection first then if it's okay you authorize him directly as I explained above, for me - as a user - that'll be more good than waiting to authorize myself in

**Comment by robertoltrocha** [comment]
I show the message that it was not possible to authenticate because he is not using the VPN, but the fields are blank. How do I access textControllers? that's what i need.

**Comment by OmarYehiaDev** [comment]
Yeah I see you but what I'm talking about is that you remove the fields if he already logged in and make it a silent authentication. I think it will be better

**Comment by robertoltrocha** [comment]
Ok I got it.
I do the automatic authentication when there is a connection with the server. When for some reason this is not possible I present the login screen.
I will adjust the login screen to just present a button to try again(without  server connection) and if the password is wrong or invalid data I will show the login screen.
